/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package osubbillingschedule

import (
	"context"

	osubbillingschedulev1beta1 "github.com/oracle/oci-service-operator/api/osubbillingschedule/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// BillingScheduleReconciler reconciles a BillingSchedule object.
type BillingScheduleReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=osubbillingschedule.oracle.com,resources=billingschedules,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=osubbillingschedule.oracle.com,resources=billingschedules/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=osubbillingschedule.oracle.com,resources=billingschedules/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *BillingScheduleReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	billingSchedule := &osubbillingschedulev1beta1.BillingSchedule{}
	return r.Reconciler.Reconcile(ctx, req, billingSchedule)
}

// SetupWithManager sets up the controller with the Manager.
func (r *BillingScheduleReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&osubbillingschedulev1beta1.BillingSchedule{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
