/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package genericartifactscontent

import (
	"context"

	genericartifactscontentv1beta1 "github.com/oracle/oci-service-operator/api/genericartifactscontent/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// GenericArtifactContentByPathReconciler reconciles a GenericArtifactContentByPath object.
type GenericArtifactContentByPathReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=genericartifactscontent.oracle.com,resources=genericartifactcontentbypaths,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=genericartifactscontent.oracle.com,resources=genericartifactcontentbypaths/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=genericartifactscontent.oracle.com,resources=genericartifactcontentbypaths/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *GenericArtifactContentByPathReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	genericArtifactContentByPath := &genericartifactscontentv1beta1.GenericArtifactContentByPath{}
	return r.Reconciler.Reconcile(ctx, req, genericArtifactContentByPath)
}

// SetupWithManager sets up the controller with the Manager.
func (r *GenericArtifactContentByPathReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&genericartifactscontentv1beta1.GenericArtifactContentByPath{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
