/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package namespace

import (
	"context"

	ocicontrolcentersdk "github.com/oracle/oci-go-sdk/v65/ocicontrolcenter"
	ocicontrolcenterv1beta1 "github.com/oracle/oci-service-operator/api/ocicontrolcenter/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type NamespaceRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *ocicontrolcenterv1beta1.Namespace, string) (any, error)
	BuildUpdateBody func(context.Context, *ocicontrolcenterv1beta1.Namespace, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*ocicontrolcenterv1beta1.Namespace]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*ocicontrolcenterv1beta1.Namespace]
	StatusHooks         generatedruntime.StatusHooks[*ocicontrolcenterv1beta1.Namespace]
	ParityHooks         generatedruntime.ParityHooks[*ocicontrolcenterv1beta1.Namespace]
	Async               generatedruntime.AsyncHooks[*ocicontrolcenterv1beta1.Namespace]
	DeleteHooks         generatedruntime.DeleteHooks[*ocicontrolcenterv1beta1.Namespace]
	List                runtimeOperationHooks[ocicontrolcentersdk.ListNamespacesRequest, ocicontrolcentersdk.ListNamespacesResponse]
	WrapGeneratedClient []func(NamespaceServiceClient) NamespaceServiceClient
}

type NamespaceRuntimeHooksMutator func(*NamespaceServiceManager, *NamespaceRuntimeHooks)

var namespaceRuntimeHooksMutators []NamespaceRuntimeHooksMutator

func registerNamespaceRuntimeHooksMutator(mutator NamespaceRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	namespaceRuntimeHooksMutators = append(namespaceRuntimeHooksMutators, mutator)
}
func newNamespaceDefaultRuntimeHooks(sdkClient ocicontrolcentersdk.OccMetricsClient) NamespaceRuntimeHooks {
	return NamespaceRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*ocicontrolcenterv1beta1.Namespace]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*ocicontrolcenterv1beta1.Namespace]{},
		StatusHooks:     generatedruntime.StatusHooks[*ocicontrolcenterv1beta1.Namespace]{},
		ParityHooks:     generatedruntime.ParityHooks[*ocicontrolcenterv1beta1.Namespace]{},
		Async:           generatedruntime.AsyncHooks[*ocicontrolcenterv1beta1.Namespace]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*ocicontrolcenterv1beta1.Namespace]{},
		List: runtimeOperationHooks[ocicontrolcentersdk.ListNamespacesRequest, ocicontrolcentersdk.ListNamespacesResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request ocicontrolcentersdk.ListNamespacesRequest) (ocicontrolcentersdk.ListNamespacesResponse, error) {
				return sdkClient.ListNamespaces(ctx, request)
			},
		},
		WrapGeneratedClient: []func(NamespaceServiceClient) NamespaceServiceClient{},
	}
}

func newNamespaceRuntimeHooks(manager *NamespaceServiceManager, sdkClient ocicontrolcentersdk.OccMetricsClient) NamespaceRuntimeHooks {
	hooks := newNamespaceDefaultRuntimeHooks(sdkClient)
	for _, mutator := range namespaceRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildNamespaceGeneratedRuntimeConfig(
	manager *NamespaceServiceManager,
	hooks NamespaceRuntimeHooks,
) generatedruntime.Config[*ocicontrolcenterv1beta1.Namespace] {
	return generatedruntime.Config[*ocicontrolcenterv1beta1.Namespace]{
		Kind:            "Namespace",
		SDKName:         "Namespace",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &ocicontrolcentersdk.ListNamespacesRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*ocicontrolcentersdk.ListNamespacesRequest))
			},
		},
	}
}

func wrapNamespaceGeneratedClient(
	hooks NamespaceRuntimeHooks,
	delegate NamespaceServiceClient,
) NamespaceServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
