/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package metricproperty

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	ocicontrolcenterv1beta1 "github.com/oracle/oci-service-operator/api/ocicontrolcenter/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type MetricPropertyServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client MetricPropertyServiceClient
}

var _ servicemanager.OSOKServiceManager = (*MetricPropertyServiceManager)(nil)

func NewMetricPropertyServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *MetricPropertyServiceManager {
	manager := &MetricPropertyServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newMetricPropertyServiceClient(manager)
	return manager
}

func NewMetricPropertyServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *MetricPropertyServiceManager {
	return NewMetricPropertyServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *MetricPropertyServiceManager) WithClient(client MetricPropertyServiceClient) *MetricPropertyServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *MetricPropertyServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *MetricPropertyServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *MetricPropertyServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *MetricPropertyServiceManager) convert(obj runtime.Object) (*ocicontrolcenterv1beta1.MetricProperty, error) {
	resource, ok := obj.(*ocicontrolcenterv1beta1.MetricProperty)
	if !ok {
		return nil, fmt.Errorf("expected *ocicontrolcenterv1beta1.MetricProperty, got %T", obj)
	}
	return resource, nil
}

func (c *MetricPropertyServiceManager) status(resource *ocicontrolcenterv1beta1.MetricProperty) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
