/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package metricproperty

import (
	"context"
	"fmt"

	ocicontrolcentersdk "github.com/oracle/oci-go-sdk/v65/ocicontrolcenter"
	ocicontrolcenterv1beta1 "github.com/oracle/oci-service-operator/api/ocicontrolcenter/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// MetricPropertyServiceClient is the handwritten extension seam for MetricProperty runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*MetricPropertyServiceManager).WithClient.
type MetricPropertyServiceClient interface {
	CreateOrUpdate(context.Context, *ocicontrolcenterv1beta1.MetricProperty, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *ocicontrolcenterv1beta1.MetricProperty) (bool, error)
}

type defaultMetricPropertyServiceClient struct {
	generatedruntime.ServiceClient[*ocicontrolcenterv1beta1.MetricProperty]
}

var _ MetricPropertyServiceClient = defaultMetricPropertyServiceClient{}

var newMetricPropertyServiceClient = func(manager *MetricPropertyServiceManager) MetricPropertyServiceClient {
	sdkClient, err := ocicontrolcentersdk.NewOccMetricsClientWithConfigurationProvider(manager.Provider)
	hooks := newMetricPropertyRuntimeHooks(manager, sdkClient)
	config := buildMetricPropertyGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize MetricProperty OCI client: %w", err)
	}
	delegate := defaultMetricPropertyServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*ocicontrolcenterv1beta1.MetricProperty](config),
	}
	return wrapMetricPropertyGeneratedClient(hooks, delegate)
}
