/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package multicloudmetadata

import (
	"context"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type MultiCloudMetadataRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *multicloudv1beta1.MultiCloudMetadata, string) (any, error)
	BuildUpdateBody func(context.Context, *multicloudv1beta1.MultiCloudMetadata, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*multicloudv1beta1.MultiCloudMetadata]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.MultiCloudMetadata]
	StatusHooks         generatedruntime.StatusHooks[*multicloudv1beta1.MultiCloudMetadata]
	ParityHooks         generatedruntime.ParityHooks[*multicloudv1beta1.MultiCloudMetadata]
	Async               generatedruntime.AsyncHooks[*multicloudv1beta1.MultiCloudMetadata]
	DeleteHooks         generatedruntime.DeleteHooks[*multicloudv1beta1.MultiCloudMetadata]
	Get                 runtimeOperationHooks[multicloudsdk.GetMultiCloudMetadataRequest, multicloudsdk.GetMultiCloudMetadataResponse]
	List                runtimeOperationHooks[multicloudsdk.ListMultiCloudMetadataRequest, multicloudsdk.ListMultiCloudMetadataResponse]
	WrapGeneratedClient []func(MultiCloudMetadataServiceClient) MultiCloudMetadataServiceClient
}

type MultiCloudMetadataRuntimeHooksMutator func(*MultiCloudMetadataServiceManager, *MultiCloudMetadataRuntimeHooks)

var multicloudmetadataRuntimeHooksMutators []MultiCloudMetadataRuntimeHooksMutator

func registerMultiCloudMetadataRuntimeHooksMutator(mutator MultiCloudMetadataRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	multicloudmetadataRuntimeHooksMutators = append(multicloudmetadataRuntimeHooksMutators, mutator)
}
func newMultiCloudMetadataDefaultRuntimeHooks(sdkClient multicloudsdk.MultiCloudsMetadataClient) MultiCloudMetadataRuntimeHooks {
	return MultiCloudMetadataRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*multicloudv1beta1.MultiCloudMetadata]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.MultiCloudMetadata]{},
		StatusHooks:     generatedruntime.StatusHooks[*multicloudv1beta1.MultiCloudMetadata]{},
		ParityHooks:     generatedruntime.ParityHooks[*multicloudv1beta1.MultiCloudMetadata]{},
		Async:           generatedruntime.AsyncHooks[*multicloudv1beta1.MultiCloudMetadata]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*multicloudv1beta1.MultiCloudMetadata]{},
		Get: runtimeOperationHooks[multicloudsdk.GetMultiCloudMetadataRequest, multicloudsdk.GetMultiCloudMetadataResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request multicloudsdk.GetMultiCloudMetadataRequest) (multicloudsdk.GetMultiCloudMetadataResponse, error) {
				return sdkClient.GetMultiCloudMetadata(ctx, request)
			},
		},
		List: runtimeOperationHooks[multicloudsdk.ListMultiCloudMetadataRequest, multicloudsdk.ListMultiCloudMetadataResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.ListMultiCloudMetadataRequest) (multicloudsdk.ListMultiCloudMetadataResponse, error) {
				return sdkClient.ListMultiCloudMetadata(ctx, request)
			},
		},
		WrapGeneratedClient: []func(MultiCloudMetadataServiceClient) MultiCloudMetadataServiceClient{},
	}
}

func newMultiCloudMetadataRuntimeHooks(manager *MultiCloudMetadataServiceManager, sdkClient multicloudsdk.MultiCloudsMetadataClient) MultiCloudMetadataRuntimeHooks {
	hooks := newMultiCloudMetadataDefaultRuntimeHooks(sdkClient)
	for _, mutator := range multicloudmetadataRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildMultiCloudMetadataGeneratedRuntimeConfig(
	manager *MultiCloudMetadataServiceManager,
	hooks MultiCloudMetadataRuntimeHooks,
) generatedruntime.Config[*multicloudv1beta1.MultiCloudMetadata] {
	return generatedruntime.Config[*multicloudv1beta1.MultiCloudMetadata]{
		Kind:            "MultiCloudMetadata",
		SDKName:         "MultiCloudMetadata",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.GetMultiCloudMetadataRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*multicloudsdk.GetMultiCloudMetadataRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.ListMultiCloudMetadataRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*multicloudsdk.ListMultiCloudMetadataRequest))
			},
		},
	}
}

func wrapMultiCloudMetadataGeneratedClient(
	hooks MultiCloudMetadataRuntimeHooks,
	delegate MultiCloudMetadataServiceClient,
) MultiCloudMetadataServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
