/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package multicloudmetadata

import (
	"context"
	"fmt"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// MultiCloudMetadataServiceClient is the handwritten extension seam for MultiCloudMetadata runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*MultiCloudMetadataServiceManager).WithClient.
type MultiCloudMetadataServiceClient interface {
	CreateOrUpdate(context.Context, *multicloudv1beta1.MultiCloudMetadata, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *multicloudv1beta1.MultiCloudMetadata) (bool, error)
}

type defaultMultiCloudMetadataServiceClient struct {
	generatedruntime.ServiceClient[*multicloudv1beta1.MultiCloudMetadata]
}

var _ MultiCloudMetadataServiceClient = defaultMultiCloudMetadataServiceClient{}

var newMultiCloudMetadataServiceClient = func(manager *MultiCloudMetadataServiceManager) MultiCloudMetadataServiceClient {
	sdkClient, err := multicloudsdk.NewMultiCloudsMetadataClientWithConfigurationProvider(manager.Provider)
	hooks := newMultiCloudMetadataRuntimeHooks(manager, sdkClient)
	config := buildMultiCloudMetadataGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize MultiCloudMetadata OCI client: %w", err)
	}
	delegate := defaultMultiCloudMetadataServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*multicloudv1beta1.MultiCloudMetadata](config),
	}
	return wrapMultiCloudMetadataGeneratedClient(hooks, delegate)
}
