/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package jmsutils

import (
	"context"

	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// AnalyzeApplicationsConfigurationReconciler reconciles a AnalyzeApplicationsConfiguration object.
type AnalyzeApplicationsConfigurationReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=jmsutils.oracle.com,resources=analyzeapplicationsconfigurations,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=jmsutils.oracle.com,resources=analyzeapplicationsconfigurations/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=jmsutils.oracle.com,resources=analyzeapplicationsconfigurations/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *AnalyzeApplicationsConfigurationReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	analyzeApplicationsConfiguration := &jmsutilsv1beta1.AnalyzeApplicationsConfiguration{}
	return r.Reconciler.Reconcile(ctx, req, analyzeApplicationsConfiguration)
}

// SetupWithManager sets up the controller with the Manager.
func (r *AnalyzeApplicationsConfigurationReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&jmsutilsv1beta1.AnalyzeApplicationsConfiguration{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
