/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package jmsutils

import (
	"context"

	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// WorkItemReconciler reconciles a WorkItem object.
type WorkItemReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=jmsutils.oracle.com,resources=workitems,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=jmsutils.oracle.com,resources=workitems/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=jmsutils.oracle.com,resources=workitems/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *WorkItemReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	workItem := &jmsutilsv1beta1.WorkItem{}
	return r.Reconciler.Reconcile(ctx, req, workItem)
}

// SetupWithManager sets up the controller with the Manager.
func (r *WorkItemReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&jmsutilsv1beta1.WorkItem{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
