/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package subscriptionacknowledgmentconfiguration

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type SubscriptionAcknowledgmentConfigurationServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client SubscriptionAcknowledgmentConfigurationServiceClient
}

var _ servicemanager.OSOKServiceManager = (*SubscriptionAcknowledgmentConfigurationServiceManager)(nil)

func NewSubscriptionAcknowledgmentConfigurationServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *SubscriptionAcknowledgmentConfigurationServiceManager {
	manager := &SubscriptionAcknowledgmentConfigurationServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newSubscriptionAcknowledgmentConfigurationServiceClient(manager)
	return manager
}

func NewSubscriptionAcknowledgmentConfigurationServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *SubscriptionAcknowledgmentConfigurationServiceManager {
	return NewSubscriptionAcknowledgmentConfigurationServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *SubscriptionAcknowledgmentConfigurationServiceManager) WithClient(client SubscriptionAcknowledgmentConfigurationServiceClient) *SubscriptionAcknowledgmentConfigurationServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *SubscriptionAcknowledgmentConfigurationServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *SubscriptionAcknowledgmentConfigurationServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *SubscriptionAcknowledgmentConfigurationServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *SubscriptionAcknowledgmentConfigurationServiceManager) convert(obj runtime.Object) (*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration, error) {
	resource, ok := obj.(*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration)
	if !ok {
		return nil, fmt.Errorf("expected *jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration, got %T", obj)
	}
	return resource, nil
}

func (c *SubscriptionAcknowledgmentConfigurationServiceManager) status(resource *jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
