/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package subscriptionacknowledgmentconfiguration

import (
	"context"
	"fmt"

	jmsutilssdk "github.com/oracle/oci-go-sdk/v65/jmsutils"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// SubscriptionAcknowledgmentConfigurationServiceClient is the handwritten extension seam for SubscriptionAcknowledgmentConfiguration runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*SubscriptionAcknowledgmentConfigurationServiceManager).WithClient.
type SubscriptionAcknowledgmentConfigurationServiceClient interface {
	CreateOrUpdate(context.Context, *jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration) (bool, error)
}

type defaultSubscriptionAcknowledgmentConfigurationServiceClient struct {
	generatedruntime.ServiceClient[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]
}

var _ SubscriptionAcknowledgmentConfigurationServiceClient = defaultSubscriptionAcknowledgmentConfigurationServiceClient{}

var newSubscriptionAcknowledgmentConfigurationServiceClient = func(manager *SubscriptionAcknowledgmentConfigurationServiceManager) SubscriptionAcknowledgmentConfigurationServiceClient {
	sdkClient, err := jmsutilssdk.NewJmsUtilsClientWithConfigurationProvider(manager.Provider)
	hooks := newSubscriptionAcknowledgmentConfigurationRuntimeHooks(manager, sdkClient)
	config := buildSubscriptionAcknowledgmentConfigurationGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize SubscriptionAcknowledgmentConfiguration OCI client: %w", err)
	}
	delegate := defaultSubscriptionAcknowledgmentConfigurationServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration](config),
	}
	return wrapSubscriptionAcknowledgmentConfigurationGeneratedClient(hooks, delegate)
}
