/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package subscriptionacknowledgmentconfiguration

import (
	"context"

	jmsutilssdk "github.com/oracle/oci-go-sdk/v65/jmsutils"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type SubscriptionAcknowledgmentConfigurationRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration, string) (any, error)
	BuildUpdateBody func(context.Context, *jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]
	StatusHooks         generatedruntime.StatusHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]
	ParityHooks         generatedruntime.ParityHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]
	Async               generatedruntime.AsyncHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]
	DeleteHooks         generatedruntime.DeleteHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]
	Get                 runtimeOperationHooks[jmsutilssdk.GetSubscriptionAcknowledgmentConfigurationRequest, jmsutilssdk.GetSubscriptionAcknowledgmentConfigurationResponse]
	Update              runtimeOperationHooks[jmsutilssdk.UpdateSubscriptionAcknowledgmentConfigurationRequest, jmsutilssdk.UpdateSubscriptionAcknowledgmentConfigurationResponse]
	WrapGeneratedClient []func(SubscriptionAcknowledgmentConfigurationServiceClient) SubscriptionAcknowledgmentConfigurationServiceClient
}

type SubscriptionAcknowledgmentConfigurationRuntimeHooksMutator func(*SubscriptionAcknowledgmentConfigurationServiceManager, *SubscriptionAcknowledgmentConfigurationRuntimeHooks)

var subscriptionacknowledgmentconfigurationRuntimeHooksMutators []SubscriptionAcknowledgmentConfigurationRuntimeHooksMutator

func registerSubscriptionAcknowledgmentConfigurationRuntimeHooksMutator(mutator SubscriptionAcknowledgmentConfigurationRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	subscriptionacknowledgmentconfigurationRuntimeHooksMutators = append(subscriptionacknowledgmentconfigurationRuntimeHooksMutators, mutator)
}
func newSubscriptionAcknowledgmentConfigurationDefaultRuntimeHooks(sdkClient jmsutilssdk.JmsUtilsClient) SubscriptionAcknowledgmentConfigurationRuntimeHooks {
	return SubscriptionAcknowledgmentConfigurationRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]{},
		StatusHooks:     generatedruntime.StatusHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]{},
		ParityHooks:     generatedruntime.ParityHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]{},
		Async:           generatedruntime.AsyncHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]{},
		Get: runtimeOperationHooks[jmsutilssdk.GetSubscriptionAcknowledgmentConfigurationRequest, jmsutilssdk.GetSubscriptionAcknowledgmentConfigurationResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request jmsutilssdk.GetSubscriptionAcknowledgmentConfigurationRequest) (jmsutilssdk.GetSubscriptionAcknowledgmentConfigurationResponse, error) {
				return sdkClient.GetSubscriptionAcknowledgmentConfiguration(ctx, request)
			},
		},
		Update: runtimeOperationHooks[jmsutilssdk.UpdateSubscriptionAcknowledgmentConfigurationRequest, jmsutilssdk.UpdateSubscriptionAcknowledgmentConfigurationResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "UpdateSubscriptionAcknowledgmentConfigurationDetails", RequestName: "UpdateSubscriptionAcknowledgmentConfigurationDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request jmsutilssdk.UpdateSubscriptionAcknowledgmentConfigurationRequest) (jmsutilssdk.UpdateSubscriptionAcknowledgmentConfigurationResponse, error) {
				return sdkClient.UpdateSubscriptionAcknowledgmentConfiguration(ctx, request)
			},
		},
		WrapGeneratedClient: []func(SubscriptionAcknowledgmentConfigurationServiceClient) SubscriptionAcknowledgmentConfigurationServiceClient{},
	}
}

func newSubscriptionAcknowledgmentConfigurationRuntimeHooks(manager *SubscriptionAcknowledgmentConfigurationServiceManager, sdkClient jmsutilssdk.JmsUtilsClient) SubscriptionAcknowledgmentConfigurationRuntimeHooks {
	hooks := newSubscriptionAcknowledgmentConfigurationDefaultRuntimeHooks(sdkClient)
	for _, mutator := range subscriptionacknowledgmentconfigurationRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildSubscriptionAcknowledgmentConfigurationGeneratedRuntimeConfig(
	manager *SubscriptionAcknowledgmentConfigurationServiceManager,
	hooks SubscriptionAcknowledgmentConfigurationRuntimeHooks,
) generatedruntime.Config[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration] {
	return generatedruntime.Config[*jmsutilsv1beta1.SubscriptionAcknowledgmentConfiguration]{
		Kind:            "SubscriptionAcknowledgmentConfiguration",
		SDKName:         "SubscriptionAcknowledgmentConfiguration",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.GetSubscriptionAcknowledgmentConfigurationRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*jmsutilssdk.GetSubscriptionAcknowledgmentConfigurationRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.UpdateSubscriptionAcknowledgmentConfigurationRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*jmsutilssdk.UpdateSubscriptionAcknowledgmentConfigurationRequest))
			},
		},
	}
}

func wrapSubscriptionAcknowledgmentConfigurationGeneratedClient(
	hooks SubscriptionAcknowledgmentConfigurationRuntimeHooks,
	delegate SubscriptionAcknowledgmentConfigurationServiceClient,
) SubscriptionAcknowledgmentConfigurationServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
