/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	genericartifactscontentv1beta1 "github.com/oracle/oci-service-operator/api/genericartifactscontent/v1beta1"
	genericartifactscontentcontrollers "github.com/oracle/oci-service-operator/controllers/genericartifactscontent"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	genericartifactscontentgenericartifactcontentservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/genericartifactscontent/genericartifactcontent"
	genericartifactscontentgenericartifactcontentbypathservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/genericartifactscontent/genericartifactcontentbypath"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "genericartifactscontent",
		AddToScheme: genericartifactscontentv1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&genericartifactscontentcontrollers.GenericArtifactContentReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"GenericArtifactContent",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return genericartifactscontentgenericartifactcontentservicemanager.NewGenericArtifactContentServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup GenericArtifactContent controller: %w", err)
			}
			if err := (&genericartifactscontentcontrollers.GenericArtifactContentByPathReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"GenericArtifactContentByPath",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return genericartifactscontentgenericartifactcontentbypathservicemanager.NewGenericArtifactContentByPathServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup GenericArtifactContentByPath controller: %w", err)
			}
			return nil
		},
	})
}
