/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	jmsutilscontrollers "github.com/oracle/oci-service-operator/controllers/jmsutils"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	jmsutilsanalyzeapplicationsconfigurationservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/jmsutils/analyzeapplicationsconfiguration"
	jmsutilsjavamigrationanalysisservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/jmsutils/javamigrationanalysis"
	jmsutilsperformancetuninganalysisservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/jmsutils/performancetuninganalysis"
	jmsutilssubscriptionacknowledgmentconfigurationservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/jmsutils/subscriptionacknowledgmentconfiguration"
	jmsutilsworkitemservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/jmsutils/workitem"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "jmsutils",
		AddToScheme: jmsutilsv1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&jmsutilscontrollers.AnalyzeApplicationsConfigurationReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"AnalyzeApplicationsConfiguration",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return jmsutilsanalyzeapplicationsconfigurationservicemanager.NewAnalyzeApplicationsConfigurationServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup AnalyzeApplicationsConfiguration controller: %w", err)
			}
			if err := (&jmsutilscontrollers.JavaMigrationAnalysisReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"JavaMigrationAnalysis",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return jmsutilsjavamigrationanalysisservicemanager.NewJavaMigrationAnalysisServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup JavaMigrationAnalysis controller: %w", err)
			}
			if err := (&jmsutilscontrollers.PerformanceTuningAnalysisReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"PerformanceTuningAnalysis",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return jmsutilsperformancetuninganalysisservicemanager.NewPerformanceTuningAnalysisServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup PerformanceTuningAnalysis controller: %w", err)
			}
			if err := (&jmsutilscontrollers.SubscriptionAcknowledgmentConfigurationReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"SubscriptionAcknowledgmentConfiguration",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return jmsutilssubscriptionacknowledgmentconfigurationservicemanager.NewSubscriptionAcknowledgmentConfigurationServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup SubscriptionAcknowledgmentConfiguration controller: %w", err)
			}
			if err := (&jmsutilscontrollers.WorkItemReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"WorkItem",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return jmsutilsworkitemservicemanager.NewWorkItemServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup WorkItem controller: %w", err)
			}
			return nil
		},
	})
}
