/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	multicloudcontrollers "github.com/oracle/oci-service-operator/controllers/multicloud"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	multicloudexternallocationdetailsmetadataservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/multicloud/externallocationdetailsmetadata"
	multicloudexternallocationmappingmetadataservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/multicloud/externallocationmappingmetadata"
	multicloudexternallocationsummariesmetadataservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/multicloud/externallocationsummariesmetadata"
	multicloudmulticloudmetadataservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/multicloud/multicloudmetadata"
	multicloudmulticloudresourceservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/multicloud/multicloudresource"
	multicloudmulticloudsubscriptionservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/multicloud/multicloudsubscription"
	multicloudnetworkanchorservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/multicloud/networkanchor"
	multicloudresourceanchorservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/multicloud/resourceanchor"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "multicloud",
		AddToScheme: multicloudv1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&multicloudcontrollers.ExternalLocationDetailsMetadataReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"ExternalLocationDetailsMetadata",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return multicloudexternallocationdetailsmetadataservicemanager.NewExternalLocationDetailsMetadataServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup ExternalLocationDetailsMetadata controller: %w", err)
			}
			if err := (&multicloudcontrollers.ExternalLocationMappingMetadataReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"ExternalLocationMappingMetadata",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return multicloudexternallocationmappingmetadataservicemanager.NewExternalLocationMappingMetadataServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup ExternalLocationMappingMetadata controller: %w", err)
			}
			if err := (&multicloudcontrollers.ExternalLocationSummariesMetadataReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"ExternalLocationSummariesMetadata",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return multicloudexternallocationsummariesmetadataservicemanager.NewExternalLocationSummariesMetadataServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup ExternalLocationSummariesMetadata controller: %w", err)
			}
			if err := (&multicloudcontrollers.MultiCloudMetadataReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"MultiCloudMetadata",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return multicloudmulticloudmetadataservicemanager.NewMultiCloudMetadataServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup MultiCloudMetadata controller: %w", err)
			}
			if err := (&multicloudcontrollers.MulticloudResourceReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"MulticloudResource",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return multicloudmulticloudresourceservicemanager.NewMulticloudResourceServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup MulticloudResource controller: %w", err)
			}
			if err := (&multicloudcontrollers.MulticloudSubscriptionReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"MulticloudSubscription",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return multicloudmulticloudsubscriptionservicemanager.NewMulticloudSubscriptionServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup MulticloudSubscription controller: %w", err)
			}
			if err := (&multicloudcontrollers.NetworkAnchorReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"NetworkAnchor",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return multicloudnetworkanchorservicemanager.NewNetworkAnchorServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup NetworkAnchor controller: %w", err)
			}
			if err := (&multicloudcontrollers.ResourceAnchorReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"ResourceAnchor",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return multicloudresourceanchorservicemanager.NewResourceAnchorServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup ResourceAnchor controller: %w", err)
			}
			return nil
		},
	})
}
