/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	ocicontrolcenterv1beta1 "github.com/oracle/oci-service-operator/api/ocicontrolcenter/v1beta1"
	ocicontrolcentercontrollers "github.com/oracle/oci-service-operator/controllers/ocicontrolcenter"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	ocicontrolcentermetricpropertyservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/ocicontrolcenter/metricproperty"
	ocicontrolcenternamespaceservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/ocicontrolcenter/namespace"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "ocicontrolcenter",
		AddToScheme: ocicontrolcenterv1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&ocicontrolcentercontrollers.MetricPropertyReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"MetricProperty",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return ocicontrolcentermetricpropertyservicemanager.NewMetricPropertyServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup MetricProperty controller: %w", err)
			}
			if err := (&ocicontrolcentercontrollers.NamespaceReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"Namespace",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return ocicontrolcenternamespaceservicemanager.NewNamespaceServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup Namespace controller: %w", err)
			}
			return nil
		},
	})
}
