/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	osuborganizationsubscriptionv1beta1 "github.com/oracle/oci-service-operator/api/osuborganizationsubscription/v1beta1"
	osuborganizationsubscriptioncontrollers "github.com/oracle/oci-service-operator/controllers/osuborganizationsubscription"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	osuborganizationsubscriptionorganizationsubscriptionservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/osuborganizationsubscription/organizationsubscription"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "osuborganizationsubscription",
		AddToScheme: osuborganizationsubscriptionv1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&osuborganizationsubscriptioncontrollers.OrganizationSubscriptionReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"OrganizationSubscription",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return osuborganizationsubscriptionorganizationsubscriptionservicemanager.NewOrganizationSubscriptionServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup OrganizationSubscription controller: %w", err)
			}
			return nil
		},
	})
}
