/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	osubbillingschedulev1beta1 "github.com/oracle/oci-service-operator/api/osubbillingschedule/v1beta1"
	osubbillingschedulecontrollers "github.com/oracle/oci-service-operator/controllers/osubbillingschedule"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	osubbillingschedulebillingscheduleservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/osubbillingschedule/billingschedule"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "osubbillingschedule",
		AddToScheme: osubbillingschedulev1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&osubbillingschedulecontrollers.BillingScheduleReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"BillingSchedule",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return osubbillingschedulebillingscheduleservicemanager.NewBillingScheduleServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup BillingSchedule controller: %w", err)
			}
			return nil
		},
	})
}
