/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package genericartifactcontent

import (
	"context"
	"fmt"

	genericartifactscontentsdk "github.com/oracle/oci-go-sdk/v65/genericartifactscontent"
	genericartifactscontentv1beta1 "github.com/oracle/oci-service-operator/api/genericartifactscontent/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// GenericArtifactContentServiceClient is the handwritten extension seam for GenericArtifactContent runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*GenericArtifactContentServiceManager).WithClient.
type GenericArtifactContentServiceClient interface {
	CreateOrUpdate(context.Context, *genericartifactscontentv1beta1.GenericArtifactContent, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *genericartifactscontentv1beta1.GenericArtifactContent) (bool, error)
}

type defaultGenericArtifactContentServiceClient struct {
	generatedruntime.ServiceClient[*genericartifactscontentv1beta1.GenericArtifactContent]
}

var _ GenericArtifactContentServiceClient = defaultGenericArtifactContentServiceClient{}

var newGenericArtifactContentServiceClient = func(manager *GenericArtifactContentServiceManager) GenericArtifactContentServiceClient {
	sdkClient, err := genericartifactscontentsdk.NewGenericArtifactsContentClientWithConfigurationProvider(manager.Provider)
	hooks := newGenericArtifactContentRuntimeHooks(manager, sdkClient)
	config := buildGenericArtifactContentGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize GenericArtifactContent OCI client: %w", err)
	}
	delegate := defaultGenericArtifactContentServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*genericartifactscontentv1beta1.GenericArtifactContent](config),
	}
	return wrapGenericArtifactContentGeneratedClient(hooks, delegate)
}
