/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package genericartifactcontent

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	genericartifactscontentv1beta1 "github.com/oracle/oci-service-operator/api/genericartifactscontent/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type GenericArtifactContentServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client GenericArtifactContentServiceClient
}

var _ servicemanager.OSOKServiceManager = (*GenericArtifactContentServiceManager)(nil)

func NewGenericArtifactContentServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *GenericArtifactContentServiceManager {
	manager := &GenericArtifactContentServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newGenericArtifactContentServiceClient(manager)
	return manager
}

func NewGenericArtifactContentServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *GenericArtifactContentServiceManager {
	return NewGenericArtifactContentServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *GenericArtifactContentServiceManager) WithClient(client GenericArtifactContentServiceClient) *GenericArtifactContentServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *GenericArtifactContentServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *GenericArtifactContentServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *GenericArtifactContentServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *GenericArtifactContentServiceManager) convert(obj runtime.Object) (*genericartifactscontentv1beta1.GenericArtifactContent, error) {
	resource, ok := obj.(*genericartifactscontentv1beta1.GenericArtifactContent)
	if !ok {
		return nil, fmt.Errorf("expected *genericartifactscontentv1beta1.GenericArtifactContent, got %T", obj)
	}
	return resource, nil
}

func (c *GenericArtifactContentServiceManager) status(resource *genericartifactscontentv1beta1.GenericArtifactContent) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
