/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package genericartifactcontent

import (
	"context"

	genericartifactscontentsdk "github.com/oracle/oci-go-sdk/v65/genericartifactscontent"
	genericartifactscontentv1beta1 "github.com/oracle/oci-service-operator/api/genericartifactscontent/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type GenericArtifactContentRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *genericartifactscontentv1beta1.GenericArtifactContent, string) (any, error)
	BuildUpdateBody func(context.Context, *genericartifactscontentv1beta1.GenericArtifactContent, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*genericartifactscontentv1beta1.GenericArtifactContent]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*genericartifactscontentv1beta1.GenericArtifactContent]
	StatusHooks         generatedruntime.StatusHooks[*genericartifactscontentv1beta1.GenericArtifactContent]
	ParityHooks         generatedruntime.ParityHooks[*genericartifactscontentv1beta1.GenericArtifactContent]
	Async               generatedruntime.AsyncHooks[*genericartifactscontentv1beta1.GenericArtifactContent]
	DeleteHooks         generatedruntime.DeleteHooks[*genericartifactscontentv1beta1.GenericArtifactContent]
	Get                 runtimeOperationHooks[genericartifactscontentsdk.GetGenericArtifactContentRequest, genericartifactscontentsdk.GetGenericArtifactContentResponse]
	WrapGeneratedClient []func(GenericArtifactContentServiceClient) GenericArtifactContentServiceClient
}

type GenericArtifactContentRuntimeHooksMutator func(*GenericArtifactContentServiceManager, *GenericArtifactContentRuntimeHooks)

var genericartifactcontentRuntimeHooksMutators []GenericArtifactContentRuntimeHooksMutator

func registerGenericArtifactContentRuntimeHooksMutator(mutator GenericArtifactContentRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	genericartifactcontentRuntimeHooksMutators = append(genericartifactcontentRuntimeHooksMutators, mutator)
}
func newGenericArtifactContentDefaultRuntimeHooks(sdkClient genericartifactscontentsdk.GenericArtifactsContentClient) GenericArtifactContentRuntimeHooks {
	return GenericArtifactContentRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*genericartifactscontentv1beta1.GenericArtifactContent]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*genericartifactscontentv1beta1.GenericArtifactContent]{},
		StatusHooks:     generatedruntime.StatusHooks[*genericartifactscontentv1beta1.GenericArtifactContent]{},
		ParityHooks:     generatedruntime.ParityHooks[*genericartifactscontentv1beta1.GenericArtifactContent]{},
		Async:           generatedruntime.AsyncHooks[*genericartifactscontentv1beta1.GenericArtifactContent]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*genericartifactscontentv1beta1.GenericArtifactContent]{},
		Get: runtimeOperationHooks[genericartifactscontentsdk.GetGenericArtifactContentRequest, genericartifactscontentsdk.GetGenericArtifactContentResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "ArtifactId", RequestName: "artifactId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request genericartifactscontentsdk.GetGenericArtifactContentRequest) (genericartifactscontentsdk.GetGenericArtifactContentResponse, error) {
				return sdkClient.GetGenericArtifactContent(ctx, request)
			},
		},
		WrapGeneratedClient: []func(GenericArtifactContentServiceClient) GenericArtifactContentServiceClient{},
	}
}

func newGenericArtifactContentRuntimeHooks(manager *GenericArtifactContentServiceManager, sdkClient genericartifactscontentsdk.GenericArtifactsContentClient) GenericArtifactContentRuntimeHooks {
	hooks := newGenericArtifactContentDefaultRuntimeHooks(sdkClient)
	for _, mutator := range genericartifactcontentRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildGenericArtifactContentGeneratedRuntimeConfig(
	manager *GenericArtifactContentServiceManager,
	hooks GenericArtifactContentRuntimeHooks,
) generatedruntime.Config[*genericartifactscontentv1beta1.GenericArtifactContent] {
	return generatedruntime.Config[*genericartifactscontentv1beta1.GenericArtifactContent]{
		Kind:            "GenericArtifactContent",
		SDKName:         "GenericArtifactContent",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &genericartifactscontentsdk.GetGenericArtifactContentRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*genericartifactscontentsdk.GetGenericArtifactContentRequest))
			},
		},
	}
}

func wrapGenericArtifactContentGeneratedClient(
	hooks GenericArtifactContentRuntimeHooks,
	delegate GenericArtifactContentServiceClient,
) GenericArtifactContentServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
