/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package multicloudsubscription

import (
	"context"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type MulticloudSubscriptionRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *multicloudv1beta1.MulticloudSubscription, string) (any, error)
	BuildUpdateBody func(context.Context, *multicloudv1beta1.MulticloudSubscription, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*multicloudv1beta1.MulticloudSubscription]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.MulticloudSubscription]
	StatusHooks         generatedruntime.StatusHooks[*multicloudv1beta1.MulticloudSubscription]
	ParityHooks         generatedruntime.ParityHooks[*multicloudv1beta1.MulticloudSubscription]
	Async               generatedruntime.AsyncHooks[*multicloudv1beta1.MulticloudSubscription]
	DeleteHooks         generatedruntime.DeleteHooks[*multicloudv1beta1.MulticloudSubscription]
	List                runtimeOperationHooks[multicloudsdk.ListMulticloudSubscriptionsRequest, multicloudsdk.ListMulticloudSubscriptionsResponse]
	WrapGeneratedClient []func(MulticloudSubscriptionServiceClient) MulticloudSubscriptionServiceClient
}

type MulticloudSubscriptionRuntimeHooksMutator func(*MulticloudSubscriptionServiceManager, *MulticloudSubscriptionRuntimeHooks)

var multicloudsubscriptionRuntimeHooksMutators []MulticloudSubscriptionRuntimeHooksMutator

func registerMulticloudSubscriptionRuntimeHooksMutator(mutator MulticloudSubscriptionRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	multicloudsubscriptionRuntimeHooksMutators = append(multicloudsubscriptionRuntimeHooksMutators, mutator)
}
func newMulticloudSubscriptionDefaultRuntimeHooks(sdkClient multicloudsdk.MulticloudsubscriptionsClient) MulticloudSubscriptionRuntimeHooks {
	return MulticloudSubscriptionRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*multicloudv1beta1.MulticloudSubscription]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.MulticloudSubscription]{},
		StatusHooks:     generatedruntime.StatusHooks[*multicloudv1beta1.MulticloudSubscription]{},
		ParityHooks:     generatedruntime.ParityHooks[*multicloudv1beta1.MulticloudSubscription]{},
		Async:           generatedruntime.AsyncHooks[*multicloudv1beta1.MulticloudSubscription]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*multicloudv1beta1.MulticloudSubscription]{},
		List: runtimeOperationHooks[multicloudsdk.ListMulticloudSubscriptionsRequest, multicloudsdk.ListMulticloudSubscriptionsResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.ListMulticloudSubscriptionsRequest) (multicloudsdk.ListMulticloudSubscriptionsResponse, error) {
				return sdkClient.ListMulticloudSubscriptions(ctx, request)
			},
		},
		WrapGeneratedClient: []func(MulticloudSubscriptionServiceClient) MulticloudSubscriptionServiceClient{},
	}
}

func newMulticloudSubscriptionRuntimeHooks(manager *MulticloudSubscriptionServiceManager, sdkClient multicloudsdk.MulticloudsubscriptionsClient) MulticloudSubscriptionRuntimeHooks {
	hooks := newMulticloudSubscriptionDefaultRuntimeHooks(sdkClient)
	for _, mutator := range multicloudsubscriptionRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildMulticloudSubscriptionGeneratedRuntimeConfig(
	manager *MulticloudSubscriptionServiceManager,
	hooks MulticloudSubscriptionRuntimeHooks,
) generatedruntime.Config[*multicloudv1beta1.MulticloudSubscription] {
	return generatedruntime.Config[*multicloudv1beta1.MulticloudSubscription]{
		Kind:            "MulticloudSubscription",
		SDKName:         "MulticloudSubscription",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.ListMulticloudSubscriptionsRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*multicloudsdk.ListMulticloudSubscriptionsRequest))
			},
		},
	}
}

func wrapMulticloudSubscriptionGeneratedClient(
	hooks MulticloudSubscriptionRuntimeHooks,
	delegate MulticloudSubscriptionServiceClient,
) MulticloudSubscriptionServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
