/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package multicloudsubscription

import (
	"context"
	"fmt"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// MulticloudSubscriptionServiceClient is the handwritten extension seam for MulticloudSubscription runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*MulticloudSubscriptionServiceManager).WithClient.
type MulticloudSubscriptionServiceClient interface {
	CreateOrUpdate(context.Context, *multicloudv1beta1.MulticloudSubscription, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *multicloudv1beta1.MulticloudSubscription) (bool, error)
}

type defaultMulticloudSubscriptionServiceClient struct {
	generatedruntime.ServiceClient[*multicloudv1beta1.MulticloudSubscription]
}

var _ MulticloudSubscriptionServiceClient = defaultMulticloudSubscriptionServiceClient{}

var newMulticloudSubscriptionServiceClient = func(manager *MulticloudSubscriptionServiceManager) MulticloudSubscriptionServiceClient {
	sdkClient, err := multicloudsdk.NewMulticloudsubscriptionsClientWithConfigurationProvider(manager.Provider)
	hooks := newMulticloudSubscriptionRuntimeHooks(manager, sdkClient)
	config := buildMulticloudSubscriptionGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize MulticloudSubscription OCI client: %w", err)
	}
	delegate := defaultMulticloudSubscriptionServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*multicloudv1beta1.MulticloudSubscription](config),
	}
	return wrapMulticloudSubscriptionGeneratedClient(hooks, delegate)
}
