/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package networkanchor

import (
	"context"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type NetworkAnchorRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *multicloudv1beta1.NetworkAnchor, string) (any, error)
	BuildUpdateBody func(context.Context, *multicloudv1beta1.NetworkAnchor, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*multicloudv1beta1.NetworkAnchor]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.NetworkAnchor]
	StatusHooks         generatedruntime.StatusHooks[*multicloudv1beta1.NetworkAnchor]
	ParityHooks         generatedruntime.ParityHooks[*multicloudv1beta1.NetworkAnchor]
	Async               generatedruntime.AsyncHooks[*multicloudv1beta1.NetworkAnchor]
	DeleteHooks         generatedruntime.DeleteHooks[*multicloudv1beta1.NetworkAnchor]
	Get                 runtimeOperationHooks[multicloudsdk.GetNetworkAnchorRequest, multicloudsdk.GetNetworkAnchorResponse]
	List                runtimeOperationHooks[multicloudsdk.ListNetworkAnchorsRequest, multicloudsdk.ListNetworkAnchorsResponse]
	WrapGeneratedClient []func(NetworkAnchorServiceClient) NetworkAnchorServiceClient
}

type NetworkAnchorRuntimeHooksMutator func(*NetworkAnchorServiceManager, *NetworkAnchorRuntimeHooks)

var networkanchorRuntimeHooksMutators []NetworkAnchorRuntimeHooksMutator

func registerNetworkAnchorRuntimeHooksMutator(mutator NetworkAnchorRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	networkanchorRuntimeHooksMutators = append(networkanchorRuntimeHooksMutators, mutator)
}
func newNetworkAnchorDefaultRuntimeHooks(sdkClient multicloudsdk.OmhubNetworkAnchorClient) NetworkAnchorRuntimeHooks {
	return NetworkAnchorRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*multicloudv1beta1.NetworkAnchor]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.NetworkAnchor]{},
		StatusHooks:     generatedruntime.StatusHooks[*multicloudv1beta1.NetworkAnchor]{},
		ParityHooks:     generatedruntime.ParityHooks[*multicloudv1beta1.NetworkAnchor]{},
		Async:           generatedruntime.AsyncHooks[*multicloudv1beta1.NetworkAnchor]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*multicloudv1beta1.NetworkAnchor]{},
		Get: runtimeOperationHooks[multicloudsdk.GetNetworkAnchorRequest, multicloudsdk.GetNetworkAnchorResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "NetworkAnchorId", RequestName: "networkAnchorId", Contribution: "path", PreferResourceID: true}, {FieldName: "SubscriptionServiceName", RequestName: "subscriptionServiceName", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "query", PreferResourceID: false}, {FieldName: "ExternalLocation", RequestName: "externalLocation", Contribution: "query", PreferResourceID: false}, {FieldName: "ShouldFetchVcnName", RequestName: "shouldFetchVcnName", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.GetNetworkAnchorRequest) (multicloudsdk.GetNetworkAnchorResponse, error) {
				return sdkClient.GetNetworkAnchor(ctx, request)
			},
		},
		List: runtimeOperationHooks[multicloudsdk.ListNetworkAnchorsRequest, multicloudsdk.ListNetworkAnchorsResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionServiceName", RequestName: "subscriptionServiceName", Contribution: "query", PreferResourceID: false}, {FieldName: "NetworkAnchorLifecycleState", RequestName: "networkAnchorLifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "ExternalLocation", RequestName: "externalLocation", Contribution: "query", PreferResourceID: false}, {FieldName: "NetworkAnchorOciSubnetId", RequestName: "networkAnchorOciSubnetId", Contribution: "query", PreferResourceID: false}, {FieldName: "CompartmentIdInSubtree", RequestName: "compartmentIdInSubtree", Contribution: "query", PreferResourceID: false}, {FieldName: "NetworkAnchorOciVcnId", RequestName: "networkAnchorOciVcnId", Contribution: "query", PreferResourceID: false}, {FieldName: "Id", RequestName: "id", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "ShouldFetchVcnName", RequestName: "shouldFetchVcnName", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.ListNetworkAnchorsRequest) (multicloudsdk.ListNetworkAnchorsResponse, error) {
				return sdkClient.ListNetworkAnchors(ctx, request)
			},
		},
		WrapGeneratedClient: []func(NetworkAnchorServiceClient) NetworkAnchorServiceClient{},
	}
}

func newNetworkAnchorRuntimeHooks(manager *NetworkAnchorServiceManager, sdkClient multicloudsdk.OmhubNetworkAnchorClient) NetworkAnchorRuntimeHooks {
	hooks := newNetworkAnchorDefaultRuntimeHooks(sdkClient)
	for _, mutator := range networkanchorRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildNetworkAnchorGeneratedRuntimeConfig(
	manager *NetworkAnchorServiceManager,
	hooks NetworkAnchorRuntimeHooks,
) generatedruntime.Config[*multicloudv1beta1.NetworkAnchor] {
	return generatedruntime.Config[*multicloudv1beta1.NetworkAnchor]{
		Kind:            "NetworkAnchor",
		SDKName:         "NetworkAnchor",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.GetNetworkAnchorRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*multicloudsdk.GetNetworkAnchorRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.ListNetworkAnchorsRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*multicloudsdk.ListNetworkAnchorsRequest))
			},
		},
	}
}

func wrapNetworkAnchorGeneratedClient(
	hooks NetworkAnchorRuntimeHooks,
	delegate NetworkAnchorServiceClient,
) NetworkAnchorServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
