/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package networkanchor

import (
	"context"
	"fmt"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// NetworkAnchorServiceClient is the handwritten extension seam for NetworkAnchor runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*NetworkAnchorServiceManager).WithClient.
type NetworkAnchorServiceClient interface {
	CreateOrUpdate(context.Context, *multicloudv1beta1.NetworkAnchor, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *multicloudv1beta1.NetworkAnchor) (bool, error)
}

type defaultNetworkAnchorServiceClient struct {
	generatedruntime.ServiceClient[*multicloudv1beta1.NetworkAnchor]
}

var _ NetworkAnchorServiceClient = defaultNetworkAnchorServiceClient{}

var newNetworkAnchorServiceClient = func(manager *NetworkAnchorServiceManager) NetworkAnchorServiceClient {
	sdkClient, err := multicloudsdk.NewOmhubNetworkAnchorClientWithConfigurationProvider(manager.Provider)
	hooks := newNetworkAnchorRuntimeHooks(manager, sdkClient)
	config := buildNetworkAnchorGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize NetworkAnchor OCI client: %w", err)
	}
	delegate := defaultNetworkAnchorServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*multicloudv1beta1.NetworkAnchor](config),
	}
	return wrapNetworkAnchorGeneratedClient(hooks, delegate)
}
