/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package networkanchor

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type NetworkAnchorServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client NetworkAnchorServiceClient
}

var _ servicemanager.OSOKServiceManager = (*NetworkAnchorServiceManager)(nil)

func NewNetworkAnchorServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *NetworkAnchorServiceManager {
	manager := &NetworkAnchorServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newNetworkAnchorServiceClient(manager)
	return manager
}

func NewNetworkAnchorServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *NetworkAnchorServiceManager {
	return NewNetworkAnchorServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *NetworkAnchorServiceManager) WithClient(client NetworkAnchorServiceClient) *NetworkAnchorServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *NetworkAnchorServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *NetworkAnchorServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *NetworkAnchorServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *NetworkAnchorServiceManager) convert(obj runtime.Object) (*multicloudv1beta1.NetworkAnchor, error) {
	resource, ok := obj.(*multicloudv1beta1.NetworkAnchor)
	if !ok {
		return nil, fmt.Errorf("expected *multicloudv1beta1.NetworkAnchor, got %T", obj)
	}
	return resource, nil
}

func (c *NetworkAnchorServiceManager) status(resource *multicloudv1beta1.NetworkAnchor) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
