/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package genericartifactcontentbypath

import (
	"context"
	"fmt"

	genericartifactscontentsdk "github.com/oracle/oci-go-sdk/v65/genericartifactscontent"
	genericartifactscontentv1beta1 "github.com/oracle/oci-service-operator/api/genericartifactscontent/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// GenericArtifactContentByPathServiceClient is the handwritten extension seam for GenericArtifactContentByPath runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*GenericArtifactContentByPathServiceManager).WithClient.
type GenericArtifactContentByPathServiceClient interface {
	CreateOrUpdate(context.Context, *genericartifactscontentv1beta1.GenericArtifactContentByPath, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *genericartifactscontentv1beta1.GenericArtifactContentByPath) (bool, error)
}

type defaultGenericArtifactContentByPathServiceClient struct {
	generatedruntime.ServiceClient[*genericartifactscontentv1beta1.GenericArtifactContentByPath]
}

var _ GenericArtifactContentByPathServiceClient = defaultGenericArtifactContentByPathServiceClient{}

var newGenericArtifactContentByPathServiceClient = func(manager *GenericArtifactContentByPathServiceManager) GenericArtifactContentByPathServiceClient {
	sdkClient, err := genericartifactscontentsdk.NewGenericArtifactsContentClientWithConfigurationProvider(manager.Provider)
	hooks := newGenericArtifactContentByPathRuntimeHooks(manager, sdkClient)
	config := buildGenericArtifactContentByPathGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize GenericArtifactContentByPath OCI client: %w", err)
	}
	delegate := defaultGenericArtifactContentByPathServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*genericartifactscontentv1beta1.GenericArtifactContentByPath](config),
	}
	return wrapGenericArtifactContentByPathGeneratedClient(hooks, delegate)
}
