/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package organizationsubscription

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	osuborganizationsubscriptionv1beta1 "github.com/oracle/oci-service-operator/api/osuborganizationsubscription/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type OrganizationSubscriptionServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client OrganizationSubscriptionServiceClient
}

var _ servicemanager.OSOKServiceManager = (*OrganizationSubscriptionServiceManager)(nil)

func NewOrganizationSubscriptionServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *OrganizationSubscriptionServiceManager {
	manager := &OrganizationSubscriptionServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newOrganizationSubscriptionServiceClient(manager)
	return manager
}

func NewOrganizationSubscriptionServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *OrganizationSubscriptionServiceManager {
	return NewOrganizationSubscriptionServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *OrganizationSubscriptionServiceManager) WithClient(client OrganizationSubscriptionServiceClient) *OrganizationSubscriptionServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *OrganizationSubscriptionServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *OrganizationSubscriptionServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *OrganizationSubscriptionServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *OrganizationSubscriptionServiceManager) convert(obj runtime.Object) (*osuborganizationsubscriptionv1beta1.OrganizationSubscription, error) {
	resource, ok := obj.(*osuborganizationsubscriptionv1beta1.OrganizationSubscription)
	if !ok {
		return nil, fmt.Errorf("expected *osuborganizationsubscriptionv1beta1.OrganizationSubscription, got %T", obj)
	}
	return resource, nil
}

func (c *OrganizationSubscriptionServiceManager) status(resource *osuborganizationsubscriptionv1beta1.OrganizationSubscription) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
