/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package organizationsubscription

import (
	"context"
	"fmt"

	osuborganizationsubscriptionsdk "github.com/oracle/oci-go-sdk/v65/osuborganizationsubscription"
	osuborganizationsubscriptionv1beta1 "github.com/oracle/oci-service-operator/api/osuborganizationsubscription/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// OrganizationSubscriptionServiceClient is the handwritten extension seam for OrganizationSubscription runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*OrganizationSubscriptionServiceManager).WithClient.
type OrganizationSubscriptionServiceClient interface {
	CreateOrUpdate(context.Context, *osuborganizationsubscriptionv1beta1.OrganizationSubscription, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *osuborganizationsubscriptionv1beta1.OrganizationSubscription) (bool, error)
}

type defaultOrganizationSubscriptionServiceClient struct {
	generatedruntime.ServiceClient[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]
}

var _ OrganizationSubscriptionServiceClient = defaultOrganizationSubscriptionServiceClient{}

var newOrganizationSubscriptionServiceClient = func(manager *OrganizationSubscriptionServiceManager) OrganizationSubscriptionServiceClient {
	sdkClient, err := osuborganizationsubscriptionsdk.NewOrganizationSubscriptionClientWithConfigurationProvider(manager.Provider)
	hooks := newOrganizationSubscriptionRuntimeHooks(manager, sdkClient)
	config := buildOrganizationSubscriptionGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize OrganizationSubscription OCI client: %w", err)
	}
	delegate := defaultOrganizationSubscriptionServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*osuborganizationsubscriptionv1beta1.OrganizationSubscription](config),
	}
	return wrapOrganizationSubscriptionGeneratedClient(hooks, delegate)
}
