/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package organizationsubscription

import (
	"context"

	osuborganizationsubscriptionsdk "github.com/oracle/oci-go-sdk/v65/osuborganizationsubscription"
	osuborganizationsubscriptionv1beta1 "github.com/oracle/oci-service-operator/api/osuborganizationsubscription/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type OrganizationSubscriptionRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *osuborganizationsubscriptionv1beta1.OrganizationSubscription, string) (any, error)
	BuildUpdateBody func(context.Context, *osuborganizationsubscriptionv1beta1.OrganizationSubscription, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]
	StatusHooks         generatedruntime.StatusHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]
	ParityHooks         generatedruntime.ParityHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]
	Async               generatedruntime.AsyncHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]
	DeleteHooks         generatedruntime.DeleteHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]
	List                runtimeOperationHooks[osuborganizationsubscriptionsdk.ListOrganizationSubscriptionsRequest, osuborganizationsubscriptionsdk.ListOrganizationSubscriptionsResponse]
	WrapGeneratedClient []func(OrganizationSubscriptionServiceClient) OrganizationSubscriptionServiceClient
}

type OrganizationSubscriptionRuntimeHooksMutator func(*OrganizationSubscriptionServiceManager, *OrganizationSubscriptionRuntimeHooks)

var organizationsubscriptionRuntimeHooksMutators []OrganizationSubscriptionRuntimeHooksMutator

func registerOrganizationSubscriptionRuntimeHooksMutator(mutator OrganizationSubscriptionRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	organizationsubscriptionRuntimeHooksMutators = append(organizationsubscriptionRuntimeHooksMutators, mutator)
}
func newOrganizationSubscriptionDefaultRuntimeHooks(sdkClient osuborganizationsubscriptionsdk.OrganizationSubscriptionClient) OrganizationSubscriptionRuntimeHooks {
	return OrganizationSubscriptionRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]{},
		StatusHooks:     generatedruntime.StatusHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]{},
		ParityHooks:     generatedruntime.ParityHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]{},
		Async:           generatedruntime.AsyncHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]{},
		List: runtimeOperationHooks[osuborganizationsubscriptionsdk.ListOrganizationSubscriptionsRequest, osuborganizationsubscriptionsdk.ListOrganizationSubscriptionsResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionIds", RequestName: "subscriptionIds", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request osuborganizationsubscriptionsdk.ListOrganizationSubscriptionsRequest) (osuborganizationsubscriptionsdk.ListOrganizationSubscriptionsResponse, error) {
				return sdkClient.ListOrganizationSubscriptions(ctx, request)
			},
		},
		WrapGeneratedClient: []func(OrganizationSubscriptionServiceClient) OrganizationSubscriptionServiceClient{},
	}
}

func newOrganizationSubscriptionRuntimeHooks(manager *OrganizationSubscriptionServiceManager, sdkClient osuborganizationsubscriptionsdk.OrganizationSubscriptionClient) OrganizationSubscriptionRuntimeHooks {
	hooks := newOrganizationSubscriptionDefaultRuntimeHooks(sdkClient)
	for _, mutator := range organizationsubscriptionRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildOrganizationSubscriptionGeneratedRuntimeConfig(
	manager *OrganizationSubscriptionServiceManager,
	hooks OrganizationSubscriptionRuntimeHooks,
) generatedruntime.Config[*osuborganizationsubscriptionv1beta1.OrganizationSubscription] {
	return generatedruntime.Config[*osuborganizationsubscriptionv1beta1.OrganizationSubscription]{
		Kind:            "OrganizationSubscription",
		SDKName:         "OrganizationSubscription",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &osuborganizationsubscriptionsdk.ListOrganizationSubscriptionsRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*osuborganizationsubscriptionsdk.ListOrganizationSubscriptionsRequest))
			},
		},
	}
}

func wrapOrganizationSubscriptionGeneratedClient(
	hooks OrganizationSubscriptionRuntimeHooks,
	delegate OrganizationSubscriptionServiceClient,
) OrganizationSubscriptionServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
