/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package externallocationsummariesmetadata

import (
	"context"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type ExternalLocationSummariesMetadataRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *multicloudv1beta1.ExternalLocationSummariesMetadata, string) (any, error)
	BuildUpdateBody func(context.Context, *multicloudv1beta1.ExternalLocationSummariesMetadata, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]
	StatusHooks         generatedruntime.StatusHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]
	ParityHooks         generatedruntime.ParityHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]
	Async               generatedruntime.AsyncHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]
	DeleteHooks         generatedruntime.DeleteHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]
	List                runtimeOperationHooks[multicloudsdk.ListExternalLocationSummariesMetadataRequest, multicloudsdk.ListExternalLocationSummariesMetadataResponse]
	WrapGeneratedClient []func(ExternalLocationSummariesMetadataServiceClient) ExternalLocationSummariesMetadataServiceClient
}

type ExternalLocationSummariesMetadataRuntimeHooksMutator func(*ExternalLocationSummariesMetadataServiceManager, *ExternalLocationSummariesMetadataRuntimeHooks)

var externallocationsummariesmetadataRuntimeHooksMutators []ExternalLocationSummariesMetadataRuntimeHooksMutator

func registerExternalLocationSummariesMetadataRuntimeHooksMutator(mutator ExternalLocationSummariesMetadataRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	externallocationsummariesmetadataRuntimeHooksMutators = append(externallocationsummariesmetadataRuntimeHooksMutators, mutator)
}
func newExternalLocationSummariesMetadataDefaultRuntimeHooks(sdkClient multicloudsdk.MetadataClient) ExternalLocationSummariesMetadataRuntimeHooks {
	return ExternalLocationSummariesMetadataRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]{},
		StatusHooks:     generatedruntime.StatusHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]{},
		ParityHooks:     generatedruntime.ParityHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]{},
		Async:           generatedruntime.AsyncHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*multicloudv1beta1.ExternalLocationSummariesMetadata]{},
		List: runtimeOperationHooks[multicloudsdk.ListExternalLocationSummariesMetadataRequest, multicloudsdk.ListExternalLocationSummariesMetadataResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "SubscriptionServiceName", RequestName: "subscriptionServiceName", Contribution: "query", PreferResourceID: false}, {FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "query", PreferResourceID: false}, {FieldName: "EntityType", RequestName: "entityType", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.ListExternalLocationSummariesMetadataRequest) (multicloudsdk.ListExternalLocationSummariesMetadataResponse, error) {
				return sdkClient.ListExternalLocationSummariesMetadata(ctx, request)
			},
		},
		WrapGeneratedClient: []func(ExternalLocationSummariesMetadataServiceClient) ExternalLocationSummariesMetadataServiceClient{},
	}
}

func newExternalLocationSummariesMetadataRuntimeHooks(manager *ExternalLocationSummariesMetadataServiceManager, sdkClient multicloudsdk.MetadataClient) ExternalLocationSummariesMetadataRuntimeHooks {
	hooks := newExternalLocationSummariesMetadataDefaultRuntimeHooks(sdkClient)
	for _, mutator := range externallocationsummariesmetadataRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildExternalLocationSummariesMetadataGeneratedRuntimeConfig(
	manager *ExternalLocationSummariesMetadataServiceManager,
	hooks ExternalLocationSummariesMetadataRuntimeHooks,
) generatedruntime.Config[*multicloudv1beta1.ExternalLocationSummariesMetadata] {
	return generatedruntime.Config[*multicloudv1beta1.ExternalLocationSummariesMetadata]{
		Kind:            "ExternalLocationSummariesMetadata",
		SDKName:         "ExternalLocationSummariesMetadata",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.ListExternalLocationSummariesMetadataRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*multicloudsdk.ListExternalLocationSummariesMetadataRequest))
			},
		},
	}
}

func wrapExternalLocationSummariesMetadataGeneratedClient(
	hooks ExternalLocationSummariesMetadataRuntimeHooks,
	delegate ExternalLocationSummariesMetadataServiceClient,
) ExternalLocationSummariesMetadataServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
