/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package externallocationsummariesmetadata

import (
	"context"
	"fmt"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ExternalLocationSummariesMetadataServiceClient is the handwritten extension seam for ExternalLocationSummariesMetadata runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*ExternalLocationSummariesMetadataServiceManager).WithClient.
type ExternalLocationSummariesMetadataServiceClient interface {
	CreateOrUpdate(context.Context, *multicloudv1beta1.ExternalLocationSummariesMetadata, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *multicloudv1beta1.ExternalLocationSummariesMetadata) (bool, error)
}

type defaultExternalLocationSummariesMetadataServiceClient struct {
	generatedruntime.ServiceClient[*multicloudv1beta1.ExternalLocationSummariesMetadata]
}

var _ ExternalLocationSummariesMetadataServiceClient = defaultExternalLocationSummariesMetadataServiceClient{}

var newExternalLocationSummariesMetadataServiceClient = func(manager *ExternalLocationSummariesMetadataServiceManager) ExternalLocationSummariesMetadataServiceClient {
	sdkClient, err := multicloudsdk.NewMetadataClientWithConfigurationProvider(manager.Provider)
	hooks := newExternalLocationSummariesMetadataRuntimeHooks(manager, sdkClient)
	config := buildExternalLocationSummariesMetadataGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize ExternalLocationSummariesMetadata OCI client: %w", err)
	}
	delegate := defaultExternalLocationSummariesMetadataServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*multicloudv1beta1.ExternalLocationSummariesMetadata](config),
	}
	return wrapExternalLocationSummariesMetadataGeneratedClient(hooks, delegate)
}
