/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package analyzeapplicationsconfiguration

import (
	"context"

	jmsutilssdk "github.com/oracle/oci-go-sdk/v65/jmsutils"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type AnalyzeApplicationsConfigurationRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *jmsutilsv1beta1.AnalyzeApplicationsConfiguration, string) (any, error)
	BuildUpdateBody func(context.Context, *jmsutilsv1beta1.AnalyzeApplicationsConfiguration, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]
	StatusHooks         generatedruntime.StatusHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]
	ParityHooks         generatedruntime.ParityHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]
	Async               generatedruntime.AsyncHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]
	DeleteHooks         generatedruntime.DeleteHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]
	Get                 runtimeOperationHooks[jmsutilssdk.GetAnalyzeApplicationsConfigurationRequest, jmsutilssdk.GetAnalyzeApplicationsConfigurationResponse]
	Update              runtimeOperationHooks[jmsutilssdk.UpdateAnalyzeApplicationsConfigurationRequest, jmsutilssdk.UpdateAnalyzeApplicationsConfigurationResponse]
	WrapGeneratedClient []func(AnalyzeApplicationsConfigurationServiceClient) AnalyzeApplicationsConfigurationServiceClient
}

type AnalyzeApplicationsConfigurationRuntimeHooksMutator func(*AnalyzeApplicationsConfigurationServiceManager, *AnalyzeApplicationsConfigurationRuntimeHooks)

var analyzeapplicationsconfigurationRuntimeHooksMutators []AnalyzeApplicationsConfigurationRuntimeHooksMutator

func registerAnalyzeApplicationsConfigurationRuntimeHooksMutator(mutator AnalyzeApplicationsConfigurationRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	analyzeapplicationsconfigurationRuntimeHooksMutators = append(analyzeapplicationsconfigurationRuntimeHooksMutators, mutator)
}
func newAnalyzeApplicationsConfigurationDefaultRuntimeHooks(sdkClient jmsutilssdk.JmsUtilsClient) AnalyzeApplicationsConfigurationRuntimeHooks {
	return AnalyzeApplicationsConfigurationRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]{},
		StatusHooks:     generatedruntime.StatusHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]{},
		ParityHooks:     generatedruntime.ParityHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]{},
		Async:           generatedruntime.AsyncHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]{},
		Get: runtimeOperationHooks[jmsutilssdk.GetAnalyzeApplicationsConfigurationRequest, jmsutilssdk.GetAnalyzeApplicationsConfigurationResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request jmsutilssdk.GetAnalyzeApplicationsConfigurationRequest) (jmsutilssdk.GetAnalyzeApplicationsConfigurationResponse, error) {
				return sdkClient.GetAnalyzeApplicationsConfiguration(ctx, request)
			},
		},
		Update: runtimeOperationHooks[jmsutilssdk.UpdateAnalyzeApplicationsConfigurationRequest, jmsutilssdk.UpdateAnalyzeApplicationsConfigurationResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "UpdateAnalyzeApplicationsConfigurationDetails", RequestName: "UpdateAnalyzeApplicationsConfigurationDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request jmsutilssdk.UpdateAnalyzeApplicationsConfigurationRequest) (jmsutilssdk.UpdateAnalyzeApplicationsConfigurationResponse, error) {
				return sdkClient.UpdateAnalyzeApplicationsConfiguration(ctx, request)
			},
		},
		WrapGeneratedClient: []func(AnalyzeApplicationsConfigurationServiceClient) AnalyzeApplicationsConfigurationServiceClient{},
	}
}

func newAnalyzeApplicationsConfigurationRuntimeHooks(manager *AnalyzeApplicationsConfigurationServiceManager, sdkClient jmsutilssdk.JmsUtilsClient) AnalyzeApplicationsConfigurationRuntimeHooks {
	hooks := newAnalyzeApplicationsConfigurationDefaultRuntimeHooks(sdkClient)
	for _, mutator := range analyzeapplicationsconfigurationRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildAnalyzeApplicationsConfigurationGeneratedRuntimeConfig(
	manager *AnalyzeApplicationsConfigurationServiceManager,
	hooks AnalyzeApplicationsConfigurationRuntimeHooks,
) generatedruntime.Config[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration] {
	return generatedruntime.Config[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]{
		Kind:            "AnalyzeApplicationsConfiguration",
		SDKName:         "AnalyzeApplicationsConfiguration",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.GetAnalyzeApplicationsConfigurationRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*jmsutilssdk.GetAnalyzeApplicationsConfigurationRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.UpdateAnalyzeApplicationsConfigurationRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*jmsutilssdk.UpdateAnalyzeApplicationsConfigurationRequest))
			},
		},
	}
}

func wrapAnalyzeApplicationsConfigurationGeneratedClient(
	hooks AnalyzeApplicationsConfigurationRuntimeHooks,
	delegate AnalyzeApplicationsConfigurationServiceClient,
) AnalyzeApplicationsConfigurationServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
