/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package analyzeapplicationsconfiguration

import (
	"context"
	"fmt"

	jmsutilssdk "github.com/oracle/oci-go-sdk/v65/jmsutils"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// AnalyzeApplicationsConfigurationServiceClient is the handwritten extension seam for AnalyzeApplicationsConfiguration runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*AnalyzeApplicationsConfigurationServiceManager).WithClient.
type AnalyzeApplicationsConfigurationServiceClient interface {
	CreateOrUpdate(context.Context, *jmsutilsv1beta1.AnalyzeApplicationsConfiguration, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *jmsutilsv1beta1.AnalyzeApplicationsConfiguration) (bool, error)
}

type defaultAnalyzeApplicationsConfigurationServiceClient struct {
	generatedruntime.ServiceClient[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration]
}

var _ AnalyzeApplicationsConfigurationServiceClient = defaultAnalyzeApplicationsConfigurationServiceClient{}

var newAnalyzeApplicationsConfigurationServiceClient = func(manager *AnalyzeApplicationsConfigurationServiceManager) AnalyzeApplicationsConfigurationServiceClient {
	sdkClient, err := jmsutilssdk.NewJmsUtilsClientWithConfigurationProvider(manager.Provider)
	hooks := newAnalyzeApplicationsConfigurationRuntimeHooks(manager, sdkClient)
	config := buildAnalyzeApplicationsConfigurationGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize AnalyzeApplicationsConfiguration OCI client: %w", err)
	}
	delegate := defaultAnalyzeApplicationsConfigurationServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*jmsutilsv1beta1.AnalyzeApplicationsConfiguration](config),
	}
	return wrapAnalyzeApplicationsConfigurationGeneratedClient(hooks, delegate)
}
