/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GenericArtifactContentByPathSpec defines the desired state of GenericArtifactContentByPath.
type GenericArtifactContentByPathSpec struct {
}

// GenericArtifactContentByPathStatus defines the observed state of GenericArtifactContentByPath.
type GenericArtifactContentByPathStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the GenericArtifactContentByPath",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the GenericArtifactContentByPath",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// GenericArtifactContentByPath is the Schema for the genericartifactcontentbypaths API.
type GenericArtifactContentByPath struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   GenericArtifactContentByPathSpec   `json:"spec,omitempty"`
	Status GenericArtifactContentByPathStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// GenericArtifactContentByPathList contains a list of GenericArtifactContentByPath.
type GenericArtifactContentByPathList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GenericArtifactContentByPath `json:"items"`
}

func init() {
	SchemeBuilder.Register(&GenericArtifactContentByPath{}, &GenericArtifactContentByPathList{})
}
