/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GenericArtifactContentByPathSpec defines the desired state of GenericArtifactContentByPath.
type GenericArtifactContentByPathSpec struct {
	// The OCID of the compartment that contains the artifact repository.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The OCID of the repository that owns the artifact content.
	RepositoryId string `json:"repositoryId,omitempty"`
	// A user-defined artifact path within the repository.
	ArtifactPath string `json:"artifactPath,omitempty"`
	// A user-defined artifact version string.
	Version string `json:"version,omitempty"`
	// A Kubernetes Secret reference containing the artifact bytes to upload.
	Content shared.SecretSource `json:"content,omitempty,omitzero"`
	// The key inside spec.content.secretName that contains the artifact bytes. Defaults to content.
	ContentKey string `json:"contentKey,omitempty"`
}

// GenericArtifactContentByPathStatus defines the observed state of GenericArtifactContentByPath.
type GenericArtifactContentByPathStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID of the artifact returned by OCI after upload.
	Id string `json:"id,omitempty"`
	// The observed repository OCID used to address the artifact content.
	RepositoryId string `json:"repositoryId,omitempty"`
	// The observed artifact path used to address the artifact content.
	ArtifactPath string `json:"artifactPath,omitempty"`
	// The observed artifact version used to address the artifact content.
	Version string `json:"version,omitempty"`
	// The observed artifact display name returned by OCI.
	DisplayName string `json:"displayName,omitempty"`
	// The observed compartment OCID returned by OCI.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The observed SHA256 digest for the artifact content.
	Sha256 string `json:"sha256,omitempty"`
	// The observed artifact size in bytes.
	SizeInBytes int64 `json:"sizeInBytes,omitempty"`
	// The observed artifact lifecycle state returned by OCI.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The latest observed entity tag for optimistic overwrite checks.
	Etag string `json:"etag,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the GenericArtifactContentByPath",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the GenericArtifactContentByPath",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// GenericArtifactContentByPath is the Schema for the genericartifactcontentbypaths API.
type GenericArtifactContentByPath struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   GenericArtifactContentByPathSpec   `json:"spec,omitempty"`
	Status GenericArtifactContentByPathStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// GenericArtifactContentByPathList contains a list of GenericArtifactContentByPath.
type GenericArtifactContentByPathList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GenericArtifactContentByPath `json:"items"`
}

func init() {
	SchemeBuilder.Register(&GenericArtifactContentByPath{}, &GenericArtifactContentByPathList{})
}
