//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericArtifactContent) DeepCopyInto(out *GenericArtifactContent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericArtifactContent.
func (in *GenericArtifactContent) DeepCopy() *GenericArtifactContent {
	if in == nil {
		return nil
	}
	out := new(GenericArtifactContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericArtifactContent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericArtifactContentByPath) DeepCopyInto(out *GenericArtifactContentByPath) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericArtifactContentByPath.
func (in *GenericArtifactContentByPath) DeepCopy() *GenericArtifactContentByPath {
	if in == nil {
		return nil
	}
	out := new(GenericArtifactContentByPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericArtifactContentByPath) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericArtifactContentByPathList) DeepCopyInto(out *GenericArtifactContentByPathList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenericArtifactContentByPath, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericArtifactContentByPathList.
func (in *GenericArtifactContentByPathList) DeepCopy() *GenericArtifactContentByPathList {
	if in == nil {
		return nil
	}
	out := new(GenericArtifactContentByPathList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericArtifactContentByPathList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericArtifactContentByPathSpec) DeepCopyInto(out *GenericArtifactContentByPathSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericArtifactContentByPathSpec.
func (in *GenericArtifactContentByPathSpec) DeepCopy() *GenericArtifactContentByPathSpec {
	if in == nil {
		return nil
	}
	out := new(GenericArtifactContentByPathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericArtifactContentByPathStatus) DeepCopyInto(out *GenericArtifactContentByPathStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericArtifactContentByPathStatus.
func (in *GenericArtifactContentByPathStatus) DeepCopy() *GenericArtifactContentByPathStatus {
	if in == nil {
		return nil
	}
	out := new(GenericArtifactContentByPathStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericArtifactContentList) DeepCopyInto(out *GenericArtifactContentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenericArtifactContent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericArtifactContentList.
func (in *GenericArtifactContentList) DeepCopy() *GenericArtifactContentList {
	if in == nil {
		return nil
	}
	out := new(GenericArtifactContentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericArtifactContentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericArtifactContentSpec) DeepCopyInto(out *GenericArtifactContentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericArtifactContentSpec.
func (in *GenericArtifactContentSpec) DeepCopy() *GenericArtifactContentSpec {
	if in == nil {
		return nil
	}
	out := new(GenericArtifactContentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericArtifactContentStatus) DeepCopyInto(out *GenericArtifactContentStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericArtifactContentStatus.
func (in *GenericArtifactContentStatus) DeepCopy() *GenericArtifactContentStatus {
	if in == nil {
		return nil
	}
	out := new(GenericArtifactContentStatus)
	in.DeepCopyInto(out)
	return out
}
