/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package ocicontrolcenter

import (
	"context"

	ocicontrolcenterv1beta1 "github.com/oracle/oci-service-operator/api/ocicontrolcenter/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// MetricPropertyReconciler reconciles a MetricProperty object.
type MetricPropertyReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=ocicontrolcenter.oracle.com,resources=metricproperties,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=ocicontrolcenter.oracle.com,resources=metricproperties/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=ocicontrolcenter.oracle.com,resources=metricproperties/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *MetricPropertyReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	metricProperty := &ocicontrolcenterv1beta1.MetricProperty{}
	return r.Reconciler.Reconcile(ctx, req, metricProperty)
}

// SetupWithManager sets up the controller with the Manager.
func (r *MetricPropertyReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&ocicontrolcenterv1beta1.MetricProperty{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
