/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package externallocationmappingmetadata

import (
	"context"
	"fmt"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ExternalLocationMappingMetadataServiceClient is the handwritten extension seam for ExternalLocationMappingMetadata runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*ExternalLocationMappingMetadataServiceManager).WithClient.
type ExternalLocationMappingMetadataServiceClient interface {
	CreateOrUpdate(context.Context, *multicloudv1beta1.ExternalLocationMappingMetadata, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *multicloudv1beta1.ExternalLocationMappingMetadata) (bool, error)
}

type defaultExternalLocationMappingMetadataServiceClient struct {
	generatedruntime.ServiceClient[*multicloudv1beta1.ExternalLocationMappingMetadata]
}

var _ ExternalLocationMappingMetadataServiceClient = defaultExternalLocationMappingMetadataServiceClient{}

var newExternalLocationMappingMetadataServiceClient = func(manager *ExternalLocationMappingMetadataServiceManager) ExternalLocationMappingMetadataServiceClient {
	sdkClient, err := multicloudsdk.NewMetadataClientWithConfigurationProvider(manager.Provider)
	hooks := newExternalLocationMappingMetadataRuntimeHooks(manager, sdkClient)
	config := buildExternalLocationMappingMetadataGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize ExternalLocationMappingMetadata OCI client: %w", err)
	}
	delegate := defaultExternalLocationMappingMetadataServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*multicloudv1beta1.ExternalLocationMappingMetadata](config),
	}
	return wrapExternalLocationMappingMetadataGeneratedClient(hooks, delegate)
}
