/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package externallocationmappingmetadata

import (
	"context"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type ExternalLocationMappingMetadataRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *multicloudv1beta1.ExternalLocationMappingMetadata, string) (any, error)
	BuildUpdateBody func(context.Context, *multicloudv1beta1.ExternalLocationMappingMetadata, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]
	StatusHooks         generatedruntime.StatusHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]
	ParityHooks         generatedruntime.ParityHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]
	Async               generatedruntime.AsyncHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]
	DeleteHooks         generatedruntime.DeleteHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]
	List                runtimeOperationHooks[multicloudsdk.ListExternalLocationMappingMetadataRequest, multicloudsdk.ListExternalLocationMappingMetadataResponse]
	WrapGeneratedClient []func(ExternalLocationMappingMetadataServiceClient) ExternalLocationMappingMetadataServiceClient
}

type ExternalLocationMappingMetadataRuntimeHooksMutator func(*ExternalLocationMappingMetadataServiceManager, *ExternalLocationMappingMetadataRuntimeHooks)

var externallocationmappingmetadataRuntimeHooksMutators []ExternalLocationMappingMetadataRuntimeHooksMutator

func registerExternalLocationMappingMetadataRuntimeHooksMutator(mutator ExternalLocationMappingMetadataRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	externallocationmappingmetadataRuntimeHooksMutators = append(externallocationmappingmetadataRuntimeHooksMutators, mutator)
}
func newExternalLocationMappingMetadataDefaultRuntimeHooks(sdkClient multicloudsdk.MetadataClient) ExternalLocationMappingMetadataRuntimeHooks {
	return ExternalLocationMappingMetadataRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]{},
		StatusHooks:     generatedruntime.StatusHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]{},
		ParityHooks:     generatedruntime.ParityHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]{},
		Async:           generatedruntime.AsyncHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*multicloudv1beta1.ExternalLocationMappingMetadata]{},
		List: runtimeOperationHooks[multicloudsdk.ListExternalLocationMappingMetadataRequest, multicloudsdk.ListExternalLocationMappingMetadataResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "SubscriptionServiceName", RequestName: "subscriptionServiceName", Contribution: "query", PreferResourceID: false}, {FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.ListExternalLocationMappingMetadataRequest) (multicloudsdk.ListExternalLocationMappingMetadataResponse, error) {
				return sdkClient.ListExternalLocationMappingMetadata(ctx, request)
			},
		},
		WrapGeneratedClient: []func(ExternalLocationMappingMetadataServiceClient) ExternalLocationMappingMetadataServiceClient{},
	}
}

func newExternalLocationMappingMetadataRuntimeHooks(manager *ExternalLocationMappingMetadataServiceManager, sdkClient multicloudsdk.MetadataClient) ExternalLocationMappingMetadataRuntimeHooks {
	hooks := newExternalLocationMappingMetadataDefaultRuntimeHooks(sdkClient)
	for _, mutator := range externallocationmappingmetadataRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildExternalLocationMappingMetadataGeneratedRuntimeConfig(
	manager *ExternalLocationMappingMetadataServiceManager,
	hooks ExternalLocationMappingMetadataRuntimeHooks,
) generatedruntime.Config[*multicloudv1beta1.ExternalLocationMappingMetadata] {
	return generatedruntime.Config[*multicloudv1beta1.ExternalLocationMappingMetadata]{
		Kind:            "ExternalLocationMappingMetadata",
		SDKName:         "ExternalLocationMappingMetadata",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.ListExternalLocationMappingMetadataRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*multicloudsdk.ListExternalLocationMappingMetadataRequest))
			},
		},
	}
}

func wrapExternalLocationMappingMetadataGeneratedClient(
	hooks ExternalLocationMappingMetadataRuntimeHooks,
	delegate ExternalLocationMappingMetadataServiceClient,
) ExternalLocationMappingMetadataServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
