/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OAuthClientCredentialSpec defines the desired state of OAuthClientCredential.
type OAuthClientCredentialSpec struct {
	// Name of the oauth credential to help user differentiate them.
	// +kubebuilder:validation:Required
	Name string `json:"name"`
	// Description of the oauth credential to help user differentiate them.
	// +kubebuilder:validation:Required
	Description string `json:"description"`
	// Allowed scopes for the given oauth credential.
	// +kubebuilder:validation:Required
	Scopes []OAuthClientCredentialScope `json:"scopes"`
	// Indicate if the password to be reset or not in the update.
	// +kubebuilder:validation:Optional
	IsResetPassword bool `json:"isResetPassword,omitempty"`
}

// OAuthClientCredentialScope defines nested fields for OAuthClientCredential.Scope.
type OAuthClientCredentialScope struct {
	// Audience for the given scope context.
	// +kubebuilder:validation:Required
	Audience string `json:"audience"`
	// Allowed permission scope for the given context.
	// +kubebuilder:validation:Required
	Scope string `json:"scope"`
}

// OAuthClientCredentialStatus defines the observed state of OAuthClientCredential.
type OAuthClientCredentialStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// Returned during create and update with password reset requests.
	Password string `json:"password,omitempty"`
	// The OCID of the user the Oauth credential belongs to.
	UserId string `json:"userId,omitempty"`
	// Date and time when this credential will expire, in the format defined by RFC3339.
	// Null if it never expires.
	// Example: `2016-08-25T21:10:29.600Z`
	ExpiresOn string `json:"expiresOn,omitempty"`
	// The OCID of the Oauth credential.
	Id string `json:"id,omitempty"`
	// The OCID of the compartment containing the Oauth credential.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The credential's current state. After creating a Oauth credential, make sure its `lifecycleState` changes from
	// CREATING to ACTIVE before using it.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// Date and time the `OAuth2ClientCredential` object was created, in the format defined by RFC3339.
	// Example: `2016-08-25T21:10:29.600Z`
	TimeCreated string `json:"timeCreated,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Name",type="string",JSONPath=".spec.name",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the OAuthClientCredential",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the OAuthClientCredential",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// OAuthClientCredential is the Schema for the oauthclientcredentials API.
type OAuthClientCredential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   OAuthClientCredentialSpec   `json:"spec,omitempty"`
	Status OAuthClientCredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// OAuthClientCredentialList contains a list of OAuthClientCredential.
type OAuthClientCredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OAuthClientCredential `json:"items"`
}

func init() {
	SchemeBuilder.Register(&OAuthClientCredential{}, &OAuthClientCredentialList{})
}
