/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BillingScheduleSpec defines the desired state of BillingSchedule.
type BillingScheduleSpec struct {
}

// BillingScheduleProduct defines nested fields for BillingSchedule.Product.
type BillingScheduleProduct struct {
	// Indicates the associated AR Invoice Number
	PartNumber string `json:"partNumber,omitempty"`
	// Product name
	Name string `json:"name,omitempty"`
}

// BillingScheduleStatus defines the observed state of BillingSchedule.
type BillingScheduleStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// Billing schedule start date
	TimeStart string `json:"timeStart,omitempty"`
	// Billing schedule end date
	TimeEnd string `json:"timeEnd,omitempty"`
	// Billing schedule invoicing date
	TimeInvoicing string `json:"timeInvoicing,omitempty"`
	// Billing schedule invoice status
	InvoiceStatus string `json:"invoiceStatus,omitempty"`
	// Billing schedule quantity
	Quantity string `json:"quantity,omitempty"`
	// Billing schedule net unit price
	NetUnitPrice string `json:"netUnitPrice,omitempty"`
	// Billing schedule line net amount
	Amount string `json:"amount,omitempty"`
	// Billing frequency
	BillingFrequency string `json:"billingFrequency,omitempty"`
	// Indicates the associated AR Invoice Number
	ArInvoiceNumber string `json:"arInvoiceNumber,omitempty"`
	// Indicates the associated AR Customer transaction id a unique identifier existing on AR.
	ArCustomerTransactionId string `json:"arCustomerTransactionId,omitempty"`
	// Order number associated with the Subscribed Service
	OrderNumber string                 `json:"orderNumber,omitempty"`
	Product     BillingScheduleProduct `json:"product,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the BillingSchedule",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the BillingSchedule",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// BillingSchedule is the Schema for the billingschedules API.
type BillingSchedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BillingScheduleSpec   `json:"spec,omitempty"`
	Status BillingScheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// BillingScheduleList contains a list of BillingSchedule.
type BillingScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BillingSchedule `json:"items"`
}

func init() {
	SchemeBuilder.Register(&BillingSchedule{}, &BillingScheduleList{})
}
