//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingSchedule) DeepCopyInto(out *BillingSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingSchedule.
func (in *BillingSchedule) DeepCopy() *BillingSchedule {
	if in == nil {
		return nil
	}
	out := new(BillingSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillingSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingScheduleList) DeepCopyInto(out *BillingScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BillingSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingScheduleList.
func (in *BillingScheduleList) DeepCopy() *BillingScheduleList {
	if in == nil {
		return nil
	}
	out := new(BillingScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillingScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingScheduleProduct) DeepCopyInto(out *BillingScheduleProduct) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingScheduleProduct.
func (in *BillingScheduleProduct) DeepCopy() *BillingScheduleProduct {
	if in == nil {
		return nil
	}
	out := new(BillingScheduleProduct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingScheduleSpec) DeepCopyInto(out *BillingScheduleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingScheduleSpec.
func (in *BillingScheduleSpec) DeepCopy() *BillingScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(BillingScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingScheduleStatus) DeepCopyInto(out *BillingScheduleStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	out.Product = in.Product
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingScheduleStatus.
func (in *BillingScheduleStatus) DeepCopy() *BillingScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(BillingScheduleStatus)
	in.DeepCopyInto(out)
	return out
}
