/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package performancetuninganalysis

import (
	"context"
	"fmt"

	jmsutilssdk "github.com/oracle/oci-go-sdk/v65/jmsutils"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// PerformanceTuningAnalysisServiceClient is the handwritten extension seam for PerformanceTuningAnalysis runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*PerformanceTuningAnalysisServiceManager).WithClient.
type PerformanceTuningAnalysisServiceClient interface {
	CreateOrUpdate(context.Context, *jmsutilsv1beta1.PerformanceTuningAnalysis, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *jmsutilsv1beta1.PerformanceTuningAnalysis) (bool, error)
}

type defaultPerformanceTuningAnalysisServiceClient struct {
	generatedruntime.ServiceClient[*jmsutilsv1beta1.PerformanceTuningAnalysis]
}

var _ PerformanceTuningAnalysisServiceClient = defaultPerformanceTuningAnalysisServiceClient{}

var newPerformanceTuningAnalysisServiceClient = func(manager *PerformanceTuningAnalysisServiceManager) PerformanceTuningAnalysisServiceClient {
	sdkClient, err := jmsutilssdk.NewJmsUtilsClientWithConfigurationProvider(manager.Provider)
	hooks := newPerformanceTuningAnalysisRuntimeHooks(manager, sdkClient)
	config := buildPerformanceTuningAnalysisGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize PerformanceTuningAnalysis OCI client: %w", err)
	}
	delegate := defaultPerformanceTuningAnalysisServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*jmsutilsv1beta1.PerformanceTuningAnalysis](config),
	}
	return wrapPerformanceTuningAnalysisGeneratedClient(hooks, delegate)
}
