/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package performancetuninganalysis

import (
	"context"

	jmsutilssdk "github.com/oracle/oci-go-sdk/v65/jmsutils"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type PerformanceTuningAnalysisRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *jmsutilsv1beta1.PerformanceTuningAnalysis, string) (any, error)
	BuildUpdateBody func(context.Context, *jmsutilsv1beta1.PerformanceTuningAnalysis, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]
	StatusHooks         generatedruntime.StatusHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]
	ParityHooks         generatedruntime.ParityHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]
	Async               generatedruntime.AsyncHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]
	DeleteHooks         generatedruntime.DeleteHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]
	Get                 runtimeOperationHooks[jmsutilssdk.GetPerformanceTuningAnalysisRequest, jmsutilssdk.GetPerformanceTuningAnalysisResponse]
	List                runtimeOperationHooks[jmsutilssdk.ListPerformanceTuningAnalysisRequest, jmsutilssdk.ListPerformanceTuningAnalysisResponse]
	Delete              runtimeOperationHooks[jmsutilssdk.DeletePerformanceTuningAnalysisRequest, jmsutilssdk.DeletePerformanceTuningAnalysisResponse]
	WrapGeneratedClient []func(PerformanceTuningAnalysisServiceClient) PerformanceTuningAnalysisServiceClient
}

type PerformanceTuningAnalysisRuntimeHooksMutator func(*PerformanceTuningAnalysisServiceManager, *PerformanceTuningAnalysisRuntimeHooks)

var performancetuninganalysisRuntimeHooksMutators []PerformanceTuningAnalysisRuntimeHooksMutator

func registerPerformanceTuningAnalysisRuntimeHooksMutator(mutator PerformanceTuningAnalysisRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	performancetuninganalysisRuntimeHooksMutators = append(performancetuninganalysisRuntimeHooksMutators, mutator)
}
func newPerformanceTuningAnalysisDefaultRuntimeHooks(sdkClient jmsutilssdk.JmsUtilsClient) PerformanceTuningAnalysisRuntimeHooks {
	return PerformanceTuningAnalysisRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]{},
		StatusHooks:     generatedruntime.StatusHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]{},
		ParityHooks:     generatedruntime.ParityHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]{},
		Async:           generatedruntime.AsyncHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*jmsutilsv1beta1.PerformanceTuningAnalysis]{},
		Get: runtimeOperationHooks[jmsutilssdk.GetPerformanceTuningAnalysisRequest, jmsutilssdk.GetPerformanceTuningAnalysisResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "PerformanceTuningAnalysisId", RequestName: "performanceTuningAnalysisId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request jmsutilssdk.GetPerformanceTuningAnalysisRequest) (jmsutilssdk.GetPerformanceTuningAnalysisResponse, error) {
				return sdkClient.GetPerformanceTuningAnalysis(ctx, request)
			},
		},
		List: runtimeOperationHooks[jmsutilssdk.ListPerformanceTuningAnalysisRequest, jmsutilssdk.ListPerformanceTuningAnalysisResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "Id", RequestName: "id", Contribution: "query", PreferResourceID: false}, {FieldName: "AnalysisProjectName", RequestName: "analysisProjectName", Contribution: "query", PreferResourceID: false}, {FieldName: "PerformanceTuningAnalysisResult", RequestName: "performanceTuningAnalysisResult", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request jmsutilssdk.ListPerformanceTuningAnalysisRequest) (jmsutilssdk.ListPerformanceTuningAnalysisResponse, error) {
				return sdkClient.ListPerformanceTuningAnalysis(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[jmsutilssdk.DeletePerformanceTuningAnalysisRequest, jmsutilssdk.DeletePerformanceTuningAnalysisResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "PerformanceTuningAnalysisId", RequestName: "performanceTuningAnalysisId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request jmsutilssdk.DeletePerformanceTuningAnalysisRequest) (jmsutilssdk.DeletePerformanceTuningAnalysisResponse, error) {
				return sdkClient.DeletePerformanceTuningAnalysis(ctx, request)
			},
		},
		WrapGeneratedClient: []func(PerformanceTuningAnalysisServiceClient) PerformanceTuningAnalysisServiceClient{},
	}
}

func newPerformanceTuningAnalysisRuntimeHooks(manager *PerformanceTuningAnalysisServiceManager, sdkClient jmsutilssdk.JmsUtilsClient) PerformanceTuningAnalysisRuntimeHooks {
	hooks := newPerformanceTuningAnalysisDefaultRuntimeHooks(sdkClient)
	for _, mutator := range performancetuninganalysisRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildPerformanceTuningAnalysisGeneratedRuntimeConfig(
	manager *PerformanceTuningAnalysisServiceManager,
	hooks PerformanceTuningAnalysisRuntimeHooks,
) generatedruntime.Config[*jmsutilsv1beta1.PerformanceTuningAnalysis] {
	return generatedruntime.Config[*jmsutilsv1beta1.PerformanceTuningAnalysis]{
		Kind:            "PerformanceTuningAnalysis",
		SDKName:         "PerformanceTuningAnalysis",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.GetPerformanceTuningAnalysisRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*jmsutilssdk.GetPerformanceTuningAnalysisRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.ListPerformanceTuningAnalysisRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*jmsutilssdk.ListPerformanceTuningAnalysisRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.DeletePerformanceTuningAnalysisRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*jmsutilssdk.DeletePerformanceTuningAnalysisRequest))
			},
		},
	}
}

func wrapPerformanceTuningAnalysisGeneratedClient(
	hooks PerformanceTuningAnalysisRuntimeHooks,
	delegate PerformanceTuningAnalysisServiceClient,
) PerformanceTuningAnalysisServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
