/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MetricPropertySpec defines the desired state of MetricProperty.
type MetricPropertySpec struct {
}

// MetricPropertyDimensions defines nested fields for MetricProperty.Dimensions.
type MetricPropertyDimensions struct {
	// The value of the dimension.
	DimensionValue string `json:"dimensionValue,omitempty"`
}

// MetricPropertyStatus defines the observed state of MetricProperty.
type MetricPropertyStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The name of the metric.
	MetricName string `json:"metricName,omitempty"`
	// Qualifiers provided in a metric definition. Available dimensions vary by metric namespace.
	Dimensions map[string]MetricPropertyDimensions `json:"dimensions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the MetricProperty",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the MetricProperty",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// MetricProperty is the Schema for the metricproperties API.
type MetricProperty struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MetricPropertySpec   `json:"spec,omitempty"`
	Status MetricPropertyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// MetricPropertyList contains a list of MetricProperty.
type MetricPropertyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MetricProperty `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MetricProperty{}, &MetricPropertyList{})
}
