/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package externallocationdetailsmetadata

import (
	"context"
	"fmt"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ExternalLocationDetailsMetadataServiceClient is the handwritten extension seam for ExternalLocationDetailsMetadata runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*ExternalLocationDetailsMetadataServiceManager).WithClient.
type ExternalLocationDetailsMetadataServiceClient interface {
	CreateOrUpdate(context.Context, *multicloudv1beta1.ExternalLocationDetailsMetadata, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *multicloudv1beta1.ExternalLocationDetailsMetadata) (bool, error)
}

type defaultExternalLocationDetailsMetadataServiceClient struct {
	generatedruntime.ServiceClient[*multicloudv1beta1.ExternalLocationDetailsMetadata]
}

var _ ExternalLocationDetailsMetadataServiceClient = defaultExternalLocationDetailsMetadataServiceClient{}

var newExternalLocationDetailsMetadataServiceClient = func(manager *ExternalLocationDetailsMetadataServiceManager) ExternalLocationDetailsMetadataServiceClient {
	sdkClient, err := multicloudsdk.NewMetadataClientWithConfigurationProvider(manager.Provider)
	hooks := newExternalLocationDetailsMetadataRuntimeHooks(manager, sdkClient)
	config := buildExternalLocationDetailsMetadataGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize ExternalLocationDetailsMetadata OCI client: %w", err)
	}
	delegate := defaultExternalLocationDetailsMetadataServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*multicloudv1beta1.ExternalLocationDetailsMetadata](config),
	}
	return wrapExternalLocationDetailsMetadataGeneratedClient(hooks, delegate)
}
