/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package externallocationdetailsmetadata

import (
	"context"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type ExternalLocationDetailsMetadataRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *multicloudv1beta1.ExternalLocationDetailsMetadata, string) (any, error)
	BuildUpdateBody func(context.Context, *multicloudv1beta1.ExternalLocationDetailsMetadata, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]
	StatusHooks         generatedruntime.StatusHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]
	ParityHooks         generatedruntime.ParityHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]
	Async               generatedruntime.AsyncHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]
	DeleteHooks         generatedruntime.DeleteHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]
	List                runtimeOperationHooks[multicloudsdk.ListExternalLocationDetailsMetadataRequest, multicloudsdk.ListExternalLocationDetailsMetadataResponse]
	WrapGeneratedClient []func(ExternalLocationDetailsMetadataServiceClient) ExternalLocationDetailsMetadataServiceClient
}

type ExternalLocationDetailsMetadataRuntimeHooksMutator func(*ExternalLocationDetailsMetadataServiceManager, *ExternalLocationDetailsMetadataRuntimeHooks)

var externallocationdetailsmetadataRuntimeHooksMutators []ExternalLocationDetailsMetadataRuntimeHooksMutator

func registerExternalLocationDetailsMetadataRuntimeHooksMutator(mutator ExternalLocationDetailsMetadataRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	externallocationdetailsmetadataRuntimeHooksMutators = append(externallocationdetailsmetadataRuntimeHooksMutators, mutator)
}
func newExternalLocationDetailsMetadataDefaultRuntimeHooks(sdkClient multicloudsdk.MetadataClient) ExternalLocationDetailsMetadataRuntimeHooks {
	return ExternalLocationDetailsMetadataRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]{},
		StatusHooks:     generatedruntime.StatusHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]{},
		ParityHooks:     generatedruntime.ParityHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]{},
		Async:           generatedruntime.AsyncHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*multicloudv1beta1.ExternalLocationDetailsMetadata]{},
		List: runtimeOperationHooks[multicloudsdk.ListExternalLocationDetailsMetadataRequest, multicloudsdk.ListExternalLocationDetailsMetadataResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionServiceName", RequestName: "subscriptionServiceName", Contribution: "query", PreferResourceID: false}, {FieldName: "EntityType", RequestName: "entityType", Contribution: "query", PreferResourceID: false}, {FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "LinkedCompartmentId", RequestName: "linkedCompartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "ExternalLocation", RequestName: "externalLocation", Contribution: "query", PreferResourceID: false}, {FieldName: "LogicalZone", RequestName: "logicalZone", Contribution: "query", PreferResourceID: false}, {FieldName: "ClusterPlacementGroupId", RequestName: "clusterPlacementGroupId", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.ListExternalLocationDetailsMetadataRequest) (multicloudsdk.ListExternalLocationDetailsMetadataResponse, error) {
				return sdkClient.ListExternalLocationDetailsMetadata(ctx, request)
			},
		},
		WrapGeneratedClient: []func(ExternalLocationDetailsMetadataServiceClient) ExternalLocationDetailsMetadataServiceClient{},
	}
}

func newExternalLocationDetailsMetadataRuntimeHooks(manager *ExternalLocationDetailsMetadataServiceManager, sdkClient multicloudsdk.MetadataClient) ExternalLocationDetailsMetadataRuntimeHooks {
	hooks := newExternalLocationDetailsMetadataDefaultRuntimeHooks(sdkClient)
	for _, mutator := range externallocationdetailsmetadataRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildExternalLocationDetailsMetadataGeneratedRuntimeConfig(
	manager *ExternalLocationDetailsMetadataServiceManager,
	hooks ExternalLocationDetailsMetadataRuntimeHooks,
) generatedruntime.Config[*multicloudv1beta1.ExternalLocationDetailsMetadata] {
	return generatedruntime.Config[*multicloudv1beta1.ExternalLocationDetailsMetadata]{
		Kind:            "ExternalLocationDetailsMetadata",
		SDKName:         "ExternalLocationDetailsMetadata",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.ListExternalLocationDetailsMetadataRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*multicloudsdk.ListExternalLocationDetailsMetadataRequest))
			},
		},
	}
}

func wrapExternalLocationDetailsMetadataGeneratedClient(
	hooks ExternalLocationDetailsMetadataRuntimeHooks,
	delegate ExternalLocationDetailsMetadataServiceClient,
) ExternalLocationDetailsMetadataServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
