/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ExternalLocationMappingMetadataSpec defines the desired state of ExternalLocationMappingMetadata.
type ExternalLocationMappingMetadataSpec struct {
}

// ExternalLocationMappingMetadataStatus defines the observed state of ExternalLocationMappingMetadata.
type ExternalLocationMappingMetadataStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the ExternalLocationMappingMetadata",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the ExternalLocationMappingMetadata",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// ExternalLocationMappingMetadata is the Schema for the externallocationmappingmetadata API.
type ExternalLocationMappingMetadata struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ExternalLocationMappingMetadataSpec   `json:"spec,omitempty"`
	Status ExternalLocationMappingMetadataStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// ExternalLocationMappingMetadataList contains a list of ExternalLocationMappingMetadata.
type ExternalLocationMappingMetadataList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExternalLocationMappingMetadata `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ExternalLocationMappingMetadata{}, &ExternalLocationMappingMetadataList{})
}
