/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ExternalLocationSummariesMetadataSpec defines the desired state of ExternalLocationSummariesMetadata.
type ExternalLocationSummariesMetadataSpec struct {
}

// ExternalLocationSummariesMetadataStatus defines the observed state of ExternalLocationSummariesMetadata.
type ExternalLocationSummariesMetadataStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the ExternalLocationSummariesMetadata",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the ExternalLocationSummariesMetadata",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// ExternalLocationSummariesMetadata is the Schema for the externallocationsummariesmetadata API.
type ExternalLocationSummariesMetadata struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ExternalLocationSummariesMetadataSpec   `json:"spec,omitempty"`
	Status ExternalLocationSummariesMetadataStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// ExternalLocationSummariesMetadataList contains a list of ExternalLocationSummariesMetadata.
type ExternalLocationSummariesMetadataList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExternalLocationSummariesMetadata `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ExternalLocationSummariesMetadata{}, &ExternalLocationSummariesMetadataList{})
}
