/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MultiCloudMetadataSpec defines the desired state of MultiCloudMetadata.
type MultiCloudMetadataSpec struct {
}

// MultiCloudMetadataStatus defines the observed state of MultiCloudMetadata.
type MultiCloudMetadataStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// MultiCloud base compartment OCID associated with subscriptionId.
	CompartmentId string `json:"compartmentId,omitempty"`
	// Oracle Cloud Infrastructure subscriptionId.
	SubscriptionId string `json:"subscriptionId,omitempty"`
	// The date and time the multicloud compartment was created, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeCreated string `json:"timeCreated,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the MultiCloudMetadata",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the MultiCloudMetadata",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// MultiCloudMetadata is the Schema for the multicloudmetadata API.
type MultiCloudMetadata struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MultiCloudMetadataSpec   `json:"spec,omitempty"`
	Status MultiCloudMetadataStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// MultiCloudMetadataList contains a list of MultiCloudMetadata.
type MultiCloudMetadataList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MultiCloudMetadata `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MultiCloudMetadata{}, &MultiCloudMetadataList{})
}
