/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MulticloudResourceSpec defines the desired state of MulticloudResource.
type MulticloudResourceSpec struct {
}

// MulticloudResourceStatus defines the observed state of MulticloudResource.
type MulticloudResourceStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The Id of the multicloud resource.
	ResourceId string `json:"resourceId,omitempty"`
	// The date and time the subscription was created, in the format defined by
	// RFC 3339 (https://tools.ietf.org/rfc/rfc3339).
	TimeCreated string `json:"timeCreated,omitempty"`
	// Endpoint used to retrieve displayName and lifeCycleState of the resource.
	ResourceDisplayName string `json:"resourceDisplayName,omitempty"`
	// What resource it refers to. Eg. VMCluster, ExaInfra, etc.
	ResourceType string `json:"resourceType,omitempty"`
	// Compartment name associated the resource.
	CompartmentName string `json:"compartmentName,omitempty"`
	// Compartment Id of the resource.
	CompartmentId string `json:"compartmentId,omitempty"`
	// Resource Anchor name.
	VcnName string `json:"vcnName,omitempty"`
	// Id of the Virtual Cloud Network associated to the resource.
	VcnId string `json:"vcnId,omitempty"`
	// Name of the network anchor associated to the resource.
	NetworkAnchorName string `json:"networkAnchorName,omitempty"`
	// OCID of the Network Anchor
	NetworkAnchorId string `json:"networkAnchorId,omitempty"`
	// Resource Id that comes from the Multi Cloud Control Plane
	CspResourceId string `json:"cspResourceId,omitempty"`
	// CSP Specific Additional Properties, AzureSubnetId for Azure
	CspAdditionalProperties map[string]string `json:"cspAdditionalProperties,omitempty"`
	// The date and time the subscription was updated, in the format defined by
	// RFC 3339 (https://tools.ietf.org/rfc/rfc3339).
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// The current state of the multicloud resource.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the MulticloudResource",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the MulticloudResource",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// MulticloudResource is the Schema for the multicloudresources API.
type MulticloudResource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MulticloudResourceSpec   `json:"spec,omitempty"`
	Status MulticloudResourceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// MulticloudResourceList contains a list of MulticloudResource.
type MulticloudResourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MulticloudResource `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MulticloudResource{}, &MulticloudResourceList{})
}
