/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MulticloudSubscriptionSpec defines the desired state of MulticloudSubscription.
type MulticloudSubscriptionSpec struct {
}

// MulticloudSubscriptionStatus defines the observed state of MulticloudSubscription.
type MulticloudSubscriptionStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// Subscription ID for OCI and Partner cloud in classic format.
	ClassicSubscriptionId string `json:"classicSubscriptionId,omitempty"`
	// The partner cloud account ID.
	PartnerCloudAccountIdentifier string `json:"partnerCloudAccountIdentifier,omitempty"`
	// The date and time the subscription was created, in the format defined by
	// RFC 3339 (https://tools.ietf.org/rfc/rfc3339).
	TimeCreated string `json:"timeCreated,omitempty"`
	// URL to the subscription page https://{console-url}/org-mgmt/subscription/ocid1.organizationssubscription.oc1.iad.amaaaaaapf266qyaqohz27zvh45jzaielgwojo53bh24s7cy5q5g7fiknpxa?region=us-ashburn-1.
	SubscriptionId string `json:"subscriptionId,omitempty"`
	// The serviceName that externalLocation map object belongs to.
	ServiceName string `json:"serviceName,omitempty"`
	// The date and time for when the multicloud was created, in the format defined by
	// RFC 3339 (https://tools.ietf.org/rfc/rfc3339).
	TimeLinkedDate string `json:"timeLinkedDate,omitempty"`
	// Payment plan for the subscription.
	PaymentPlan string `json:"paymentPlan,omitempty"`
	// Total value for the subscription.
	ActiveCommitment string `json:"activeCommitment,omitempty"`
	// The date and time for when the subscription is finishing, in the format defined by
	// RFC 3339 (https://tools.ietf.org/rfc/rfc3339).
	TimeEndDate string `json:"timeEndDate,omitempty"`
	// The current state of the subscription.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// CSP Specific Additional Properties, AzureSubnetId for Azure
	CspAdditionalProperties map[string]string `json:"cspAdditionalProperties,omitempty"`
	// The date and time the subscription was updated, in the format defined by
	// RFC 3339 (https://tools.ietf.org/rfc/rfc3339).
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the MulticloudSubscription",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the MulticloudSubscription",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// MulticloudSubscription is the Schema for the multicloudsubscriptions API.
type MulticloudSubscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MulticloudSubscriptionSpec   `json:"spec,omitempty"`
	Status MulticloudSubscriptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// MulticloudSubscriptionList contains a list of MulticloudSubscription.
type MulticloudSubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MulticloudSubscription `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MulticloudSubscription{}, &MulticloudSubscriptionList{})
}
