/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NetworkAnchorSpec defines the desired state of NetworkAnchor.
type NetworkAnchorSpec struct {
}

// NetworkAnchorOciMetadataItemVcn defines nested fields for NetworkAnchor.OciMetadataItem.Vcn.
type NetworkAnchorOciMetadataItemVcn struct {
	// Oracle Cloud Infrastructure VCN OCID. CSP can not set this property.
	VcnId string `json:"vcnId,omitempty"`
	// Name of the VCN associated to the Network Anchor.
	VcnName string `json:"vcnName,omitempty"`
	// Oracle Cloud Infrastructure primary cidr block. CSP can set this property
	// It's optional only if disconnect anchor is allowed
	// IPv4 CIDR blocks for the VCN that meet the following criteria
	// Type: [string (length: 1–32), ...]
	// The CIDR blocks must be valid.
	// They must not overlap with each other or with the on-premises network CIDR block.
	CidrBlocks []string `json:"cidrBlocks,omitempty"`
	// Oracle Cloud Infrastructure backup cidr block. CSP can set this property
	// It's optional only if disconnect anchor is allowed.
	// IPv4 CIDR blocks for the VCN that meet the following criteria
	// Type: [string (length: 1–32), ...]
	// The CIDR blocks must be valid.
	// They must not overlap with each other or with the on-premises network CIDR block.
	BackupCidrBlocks []string `json:"backupCidrBlocks,omitempty"`
	// Oracle Cloud Infrastructure DNS label. This is optional if DNS config is provided.
	DnsLabel string `json:"dnsLabel,omitempty"`
}

// NetworkAnchorOciMetadataItemDns defines nested fields for NetworkAnchor.OciMetadataItem.Dns.
type NetworkAnchorOciMetadataItemDns struct {
	// Full custom domain name. If this field is passed dnsLabel will be ignored
	CustomDomainName string `json:"customDomainName,omitempty"`
}

// NetworkAnchorOciMetadataItemSubnet defines nested fields for NetworkAnchor.OciMetadataItem.Subnet.
type NetworkAnchorOciMetadataItemSubnet struct {
	// Defines if the subnet is the primary or backup for the network
	Type string `json:"type,omitempty"`
	// OCID for existing the subnet. CSP can not set this property.
	SubnetId string `json:"subnetId,omitempty"`
	// Subnet label. CSP can set this property
	Label string `json:"label,omitempty"`
}

// NetworkAnchorOciMetadataItem defines nested fields for NetworkAnchor.OciMetadataItem.
type NetworkAnchorOciMetadataItem struct {
	// Defines status of the Network Anchor.
	NetworkAnchorConnectionStatus string                          `json:"networkAnchorConnectionStatus,omitempty"`
	Vcn                           NetworkAnchorOciMetadataItemVcn `json:"vcn,omitempty"`
	Dns                           NetworkAnchorOciMetadataItemDns `json:"dns,omitempty"`
	// Network subnets
	Subnets []NetworkAnchorOciMetadataItemSubnet `json:"subnets,omitempty"`
	// The DNS Listener Endpoint Address.
	DnsListeningEndpointIpAddress string `json:"dnsListeningEndpointIpAddress,omitempty"`
	// The DNS Listener Forwarding Address.
	DnsForwardingEndpointIpAddress string `json:"dnsForwardingEndpointIpAddress,omitempty"`
	// DNS forward configuration
	DnsForwardingConfig []map[string]string `json:"dnsForwardingConfig,omitempty"`
}

// NetworkAnchorCloudServiceProviderMetadataItem defines nested fields for NetworkAnchor.CloudServiceProviderMetadataItem.
type NetworkAnchorCloudServiceProviderMetadataItem struct {
	// Azure/GCP/AWS region
	Region string `json:"region,omitempty"`
	// CSP oracle database network anchor unique ID/name
	OdbNetworkId string `json:"odbNetworkId,omitempty"`
	// An Azure/GCP/AWS cidrBlocks
	CidrBlocks []string `json:"cidrBlocks,omitempty"`
	// CSP network anchor Uri
	NetworkAnchorUri string `json:"networkAnchorUri,omitempty"`
	// CSP Specific Additional Properties, AzureSubnetId for Azure
	CspAdditionalProperties map[string]string `json:"cspAdditionalProperties,omitempty"`
	// DNS domain ip mapping forwarding configuration
	DnsForwardingConfig []map[string]string `json:"dnsForwardingConfig,omitempty"`
}

// NetworkAnchorStatus defines the observed state of NetworkAnchor.
type NetworkAnchorStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the NetworkAnchor.
	Id string `json:"id,omitempty"`
	// A user-friendly name. Does not have to be unique, and it's changeable.
	DisplayName string `json:"displayName,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
	CompartmentId string `json:"compartmentId,omitempty"`
	// OCI resource anchor Id (OCID).
	ResourceAnchorId string `json:"resourceAnchorId,omitempty"`
	// The date and time the NetworkAnchor was created, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeCreated string `json:"timeCreated,omitempty"`
	// The current state of the NetworkAnchor.
	NetworkAnchorLifecycleState string `json:"networkAnchorLifecycleState,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// The date and time the NetworkAnchor was updated, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// A message that describes the current state of the NetworkAnchor in more detail. For example,
	// can be used to provide actionable information for a resource in the Failed state.
	LifecycleDetails string `json:"lifecycleDetails,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
	// AUTO_BIND - when passed compartment will be created on-behalf of customer and bind to this resource anchor
	// NO_AUTO_BIND - compartment will not be created and later customer can bind existing compartment.
	// to this resource anchor. This is for future use only
	SetupMode string `json:"setupMode,omitempty"`
	// The CPG ID in which Network Anchor will be created.
	ClusterPlacementGroupId          string                                        `json:"clusterPlacementGroupId,omitempty"`
	OciMetadataItem                  NetworkAnchorOciMetadataItem                  `json:"ociMetadataItem,omitempty"`
	CloudServiceProviderMetadataItem NetworkAnchorCloudServiceProviderMetadataItem `json:"cloudServiceProviderMetadataItem,omitempty"`
	// Oracle Cloud Infrastructure Subscription Type.
	SubscriptionType string `json:"subscriptionType,omitempty"`
	// Defines status of the Network Anchor.
	NetworkAnchorConnectionStatus string `json:"networkAnchorConnectionStatus,omitempty"`
	// OCI resource Id of VCN.
	VcnId string `json:"vcnId,omitempty"`
	// Name of the VCN associated to the Network Anchor.
	VcnName string `json:"vcnName,omitempty"`
	// CSP Specific Additional Properties, AzureSubnetId for Azure
	CspAdditionalProperties map[string]string `json:"cspAdditionalProperties,omitempty"`
	// Network Anchor Id in the Cloud Service Provider.
	CspNetworkAnchorId string `json:"cspNetworkAnchorId,omitempty"`
	// CSP network anchor Uri
	NetworkAnchorUri string `json:"networkAnchorUri,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the NetworkAnchor",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the NetworkAnchor",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// NetworkAnchor is the Schema for the networkanchors API.
type NetworkAnchor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NetworkAnchorSpec   `json:"spec,omitempty"`
	Status NetworkAnchorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// NetworkAnchorList contains a list of NetworkAnchor.
type NetworkAnchorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkAnchor `json:"items"`
}

func init() {
	SchemeBuilder.Register(&NetworkAnchor{}, &NetworkAnchorList{})
}
