/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ResourceAnchorSpec defines the desired state of ResourceAnchor.
type ResourceAnchorSpec struct {
}

// ResourceAnchorCloudServiceProviderMetadataItem defines nested fields for ResourceAnchor.CloudServiceProviderMetadataItem.
type ResourceAnchorCloudServiceProviderMetadataItem struct {
	JsonData string `json:"jsonData,omitempty"`
	// The Azure, AWS or GCP region.
	Region string `json:"region,omitempty"`
	// CSP resource anchor ID.
	CspResourceAnchorId string `json:"cspResourceAnchorId,omitempty"`
	// CSP resource anchor name.
	CspResourceAnchorName string `json:"cspResourceAnchorName,omitempty"`
	// CSP resource anchor Uri.
	ResourceAnchorUri string `json:"resourceAnchorUri,omitempty"`
	// CSP Specific Additional Properties, AzureSubnetId for Azure
	CspAdditionalProperties map[string]string `json:"cspAdditionalProperties,omitempty"`
	// OCI resource anchor name.
	ResourceAnchorName string `json:"resourceAnchorName,omitempty"`
	SubscriptionType   string `json:"subscriptionType,omitempty"`
	// Azure resource group that was used for creating this resource.
	ResourceGroup string `json:"resourceGroup,omitempty"`
	// Azure subscription that was used for creating this resource.
	Subscription string `json:"subscription,omitempty"`
	// GCP project number that was used for creating this resource anchor resource.
	ProjectNumber string `json:"projectNumber,omitempty"`
	// AWS accountId that was used for creating this resource anchor resource.
	AccountId string `json:"accountId,omitempty"`
}

// ResourceAnchorStatus defines the observed state of ResourceAnchor.
type ResourceAnchorStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the ResourceAnchor.
	Id string `json:"id,omitempty"`
	// A user-friendly name. Does not have to be unique, and it's changeable.
	DisplayName string `json:"displayName,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The date and time the ResourceAnchor was created, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeCreated string `json:"timeCreated,omitempty"`
	// The current state of the ResourceAnchor.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
	// Oracle Cloud Infrastructure Subscription Id
	SubscriptionId string `json:"subscriptionId,omitempty"`
	// OCI Region that resource is created.
	Region string `json:"region,omitempty"`
	// The name assigned to the compartment during creation.
	CompartmentName string `json:"compartmentName,omitempty"`
	// The date and time the ResourceAnchor was updated, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// A message that describes the current state of the ResourceAnchor in more detail. For example,
	// can be used to provide actionable information for a resource in the Failed state.
	LifecycleDetails string `json:"lifecycleDetails,omitempty"`
	// AUTO_BIND - when passed compartment will be created on-behalf of customer and bind to this resource anchor
	// NO_AUTO_BIND - compartment will not be created and later customer can bind existing compartment.
	// to this resource anchor. This is for future use only
	SetupMode string `json:"setupMode,omitempty"`
	// Optional - Oracle Cloud Infrastructure compartment Id (OCID) which was created or linked by customer with resource anchor.
	// This compartmentId is different from where resource Anchor live.
	LinkedCompartmentId string `json:"linkedCompartmentId,omitempty"`
	// The name assigned to the compartment which was created or linked by customer with resource anchor. This compartment is different from where resource Anchor live.
	LinkedCompartmentName string `json:"linkedCompartmentName,omitempty"`
	// subscription type
	SubscriptionType                 string                                         `json:"subscriptionType,omitempty"`
	CloudServiceProviderMetadataItem ResourceAnchorCloudServiceProviderMetadataItem `json:"cloudServiceProviderMetadataItem,omitempty"`
	// Partner Cloud Account Identifier of the Cloud Service Provider.
	PartnerCloudAccountIdentifier string `json:"partnerCloudAccountIdentifier,omitempty"`
	// Resource Anchor Id in the Cloud Service Provider.
	CspResourceAnchorId string `json:"cspResourceAnchorId,omitempty"`
	// Resource Anchor Name in the Cloud Service Provider.
	CspResourceAnchorName string `json:"cspResourceAnchorName,omitempty"`
	// CSP Specific Additional Properties, AzureSubnetId for Azure
	CspAdditionalProperties map[string]string `json:"cspAdditionalProperties,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the ResourceAnchor",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the ResourceAnchor",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// ResourceAnchor is the Schema for the resourceanchors API.
type ResourceAnchor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ResourceAnchorSpec   `json:"spec,omitempty"`
	Status ResourceAnchorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// ResourceAnchorList contains a list of ResourceAnchor.
type ResourceAnchorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ResourceAnchor `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ResourceAnchor{}, &ResourceAnchorList{})
}
