/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package resourceanchor

import (
	"context"
	"fmt"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ResourceAnchorServiceClient is the handwritten extension seam for ResourceAnchor runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*ResourceAnchorServiceManager).WithClient.
type ResourceAnchorServiceClient interface {
	CreateOrUpdate(context.Context, *multicloudv1beta1.ResourceAnchor, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *multicloudv1beta1.ResourceAnchor) (bool, error)
}

type defaultResourceAnchorServiceClient struct {
	generatedruntime.ServiceClient[*multicloudv1beta1.ResourceAnchor]
}

var _ ResourceAnchorServiceClient = defaultResourceAnchorServiceClient{}

var newResourceAnchorServiceClient = func(manager *ResourceAnchorServiceManager) ResourceAnchorServiceClient {
	sdkClient, err := multicloudsdk.NewOmhubResourceAnchorClientWithConfigurationProvider(manager.Provider)
	hooks := newResourceAnchorRuntimeHooks(manager, sdkClient)
	config := buildResourceAnchorGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize ResourceAnchor OCI client: %w", err)
	}
	delegate := defaultResourceAnchorServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*multicloudv1beta1.ResourceAnchor](config),
	}
	return wrapResourceAnchorGeneratedClient(hooks, delegate)
}
