/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package resourceanchor

import (
	"context"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type ResourceAnchorRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *multicloudv1beta1.ResourceAnchor, string) (any, error)
	BuildUpdateBody func(context.Context, *multicloudv1beta1.ResourceAnchor, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*multicloudv1beta1.ResourceAnchor]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.ResourceAnchor]
	StatusHooks         generatedruntime.StatusHooks[*multicloudv1beta1.ResourceAnchor]
	ParityHooks         generatedruntime.ParityHooks[*multicloudv1beta1.ResourceAnchor]
	Async               generatedruntime.AsyncHooks[*multicloudv1beta1.ResourceAnchor]
	DeleteHooks         generatedruntime.DeleteHooks[*multicloudv1beta1.ResourceAnchor]
	Get                 runtimeOperationHooks[multicloudsdk.GetResourceAnchorRequest, multicloudsdk.GetResourceAnchorResponse]
	List                runtimeOperationHooks[multicloudsdk.ListResourceAnchorsRequest, multicloudsdk.ListResourceAnchorsResponse]
	WrapGeneratedClient []func(ResourceAnchorServiceClient) ResourceAnchorServiceClient
}

type ResourceAnchorRuntimeHooksMutator func(*ResourceAnchorServiceManager, *ResourceAnchorRuntimeHooks)

var resourceanchorRuntimeHooksMutators []ResourceAnchorRuntimeHooksMutator

func registerResourceAnchorRuntimeHooksMutator(mutator ResourceAnchorRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	resourceanchorRuntimeHooksMutators = append(resourceanchorRuntimeHooksMutators, mutator)
}
func newResourceAnchorDefaultRuntimeHooks(sdkClient multicloudsdk.OmhubResourceAnchorClient) ResourceAnchorRuntimeHooks {
	return ResourceAnchorRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*multicloudv1beta1.ResourceAnchor]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.ResourceAnchor]{},
		StatusHooks:     generatedruntime.StatusHooks[*multicloudv1beta1.ResourceAnchor]{},
		ParityHooks:     generatedruntime.ParityHooks[*multicloudv1beta1.ResourceAnchor]{},
		Async:           generatedruntime.AsyncHooks[*multicloudv1beta1.ResourceAnchor]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*multicloudv1beta1.ResourceAnchor]{},
		Get: runtimeOperationHooks[multicloudsdk.GetResourceAnchorRequest, multicloudsdk.GetResourceAnchorResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "ResourceAnchorId", RequestName: "resourceAnchorId", Contribution: "path", PreferResourceID: true}, {FieldName: "SubscriptionServiceName", RequestName: "subscriptionServiceName", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "query", PreferResourceID: false}, {FieldName: "ShouldFetchCompartmentName", RequestName: "shouldFetchCompartmentName", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.GetResourceAnchorRequest) (multicloudsdk.GetResourceAnchorResponse, error) {
				return sdkClient.GetResourceAnchor(ctx, request)
			},
		},
		List: runtimeOperationHooks[multicloudsdk.ListResourceAnchorsRequest, multicloudsdk.ListResourceAnchorsResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "LinkedCompartmentId", RequestName: "linkedCompartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "LifecycleState", RequestName: "lifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "Id", RequestName: "id", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}, {FieldName: "IsCompartmentIdInSubtree", RequestName: "isCompartmentIdInSubtree", Contribution: "query", PreferResourceID: false}, {FieldName: "ShouldFetchCompartmentName", RequestName: "shouldFetchCompartmentName", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionServiceName", RequestName: "subscriptionServiceName", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.ListResourceAnchorsRequest) (multicloudsdk.ListResourceAnchorsResponse, error) {
				return sdkClient.ListResourceAnchors(ctx, request)
			},
		},
		WrapGeneratedClient: []func(ResourceAnchorServiceClient) ResourceAnchorServiceClient{},
	}
}

func newResourceAnchorRuntimeHooks(manager *ResourceAnchorServiceManager, sdkClient multicloudsdk.OmhubResourceAnchorClient) ResourceAnchorRuntimeHooks {
	hooks := newResourceAnchorDefaultRuntimeHooks(sdkClient)
	for _, mutator := range resourceanchorRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildResourceAnchorGeneratedRuntimeConfig(
	manager *ResourceAnchorServiceManager,
	hooks ResourceAnchorRuntimeHooks,
) generatedruntime.Config[*multicloudv1beta1.ResourceAnchor] {
	return generatedruntime.Config[*multicloudv1beta1.ResourceAnchor]{
		Kind:            "ResourceAnchor",
		SDKName:         "ResourceAnchor",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.GetResourceAnchorRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*multicloudsdk.GetResourceAnchorRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.ListResourceAnchorsRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*multicloudsdk.ListResourceAnchorsRequest))
			},
		},
	}
}

func wrapResourceAnchorGeneratedClient(
	hooks ResourceAnchorRuntimeHooks,
	delegate ResourceAnchorServiceClient,
) ResourceAnchorServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
