/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package billingschedule

import (
	"context"

	osubbillingschedulesdk "github.com/oracle/oci-go-sdk/v65/osubbillingschedule"
	osubbillingschedulev1beta1 "github.com/oracle/oci-service-operator/api/osubbillingschedule/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type BillingScheduleRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *osubbillingschedulev1beta1.BillingSchedule, string) (any, error)
	BuildUpdateBody func(context.Context, *osubbillingschedulev1beta1.BillingSchedule, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*osubbillingschedulev1beta1.BillingSchedule]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*osubbillingschedulev1beta1.BillingSchedule]
	StatusHooks         generatedruntime.StatusHooks[*osubbillingschedulev1beta1.BillingSchedule]
	ParityHooks         generatedruntime.ParityHooks[*osubbillingschedulev1beta1.BillingSchedule]
	Async               generatedruntime.AsyncHooks[*osubbillingschedulev1beta1.BillingSchedule]
	DeleteHooks         generatedruntime.DeleteHooks[*osubbillingschedulev1beta1.BillingSchedule]
	List                runtimeOperationHooks[osubbillingschedulesdk.ListBillingSchedulesRequest, osubbillingschedulesdk.ListBillingSchedulesResponse]
	WrapGeneratedClient []func(BillingScheduleServiceClient) BillingScheduleServiceClient
}

type BillingScheduleRuntimeHooksMutator func(*BillingScheduleServiceManager, *BillingScheduleRuntimeHooks)

var billingscheduleRuntimeHooksMutators []BillingScheduleRuntimeHooksMutator

func registerBillingScheduleRuntimeHooksMutator(mutator BillingScheduleRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	billingscheduleRuntimeHooksMutators = append(billingscheduleRuntimeHooksMutators, mutator)
}
func newBillingScheduleDefaultRuntimeHooks(sdkClient osubbillingschedulesdk.BillingScheduleClient) BillingScheduleRuntimeHooks {
	return BillingScheduleRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*osubbillingschedulev1beta1.BillingSchedule]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*osubbillingschedulev1beta1.BillingSchedule]{},
		StatusHooks:     generatedruntime.StatusHooks[*osubbillingschedulev1beta1.BillingSchedule]{},
		ParityHooks:     generatedruntime.ParityHooks[*osubbillingschedulev1beta1.BillingSchedule]{},
		Async:           generatedruntime.AsyncHooks[*osubbillingschedulev1beta1.BillingSchedule]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*osubbillingschedulev1beta1.BillingSchedule]{},
		List: runtimeOperationHooks[osubbillingschedulesdk.ListBillingSchedulesRequest, osubbillingschedulesdk.ListBillingSchedulesResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscribedServiceId", RequestName: "subscribedServiceId", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request osubbillingschedulesdk.ListBillingSchedulesRequest) (osubbillingschedulesdk.ListBillingSchedulesResponse, error) {
				return sdkClient.ListBillingSchedules(ctx, request)
			},
		},
		WrapGeneratedClient: []func(BillingScheduleServiceClient) BillingScheduleServiceClient{},
	}
}

func newBillingScheduleRuntimeHooks(manager *BillingScheduleServiceManager, sdkClient osubbillingschedulesdk.BillingScheduleClient) BillingScheduleRuntimeHooks {
	hooks := newBillingScheduleDefaultRuntimeHooks(sdkClient)
	for _, mutator := range billingscheduleRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildBillingScheduleGeneratedRuntimeConfig(
	manager *BillingScheduleServiceManager,
	hooks BillingScheduleRuntimeHooks,
) generatedruntime.Config[*osubbillingschedulev1beta1.BillingSchedule] {
	return generatedruntime.Config[*osubbillingschedulev1beta1.BillingSchedule]{
		Kind:            "BillingSchedule",
		SDKName:         "BillingSchedule",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &osubbillingschedulesdk.ListBillingSchedulesRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*osubbillingschedulesdk.ListBillingSchedulesRequest))
			},
		},
	}
}

func wrapBillingScheduleGeneratedClient(
	hooks BillingScheduleRuntimeHooks,
	delegate BillingScheduleServiceClient,
) BillingScheduleServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
