/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package billingschedule

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	osubbillingschedulev1beta1 "github.com/oracle/oci-service-operator/api/osubbillingschedule/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type BillingScheduleServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client BillingScheduleServiceClient
}

var _ servicemanager.OSOKServiceManager = (*BillingScheduleServiceManager)(nil)

func NewBillingScheduleServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *BillingScheduleServiceManager {
	manager := &BillingScheduleServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newBillingScheduleServiceClient(manager)
	return manager
}

func NewBillingScheduleServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *BillingScheduleServiceManager {
	return NewBillingScheduleServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *BillingScheduleServiceManager) WithClient(client BillingScheduleServiceClient) *BillingScheduleServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *BillingScheduleServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *BillingScheduleServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *BillingScheduleServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *BillingScheduleServiceManager) convert(obj runtime.Object) (*osubbillingschedulev1beta1.BillingSchedule, error) {
	resource, ok := obj.(*osubbillingschedulev1beta1.BillingSchedule)
	if !ok {
		return nil, fmt.Errorf("expected *osubbillingschedulev1beta1.BillingSchedule, got %T", obj)
	}
	return resource, nil
}

func (c *BillingScheduleServiceManager) status(resource *osubbillingschedulev1beta1.BillingSchedule) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
