/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package billingschedule

import (
	"context"
	"fmt"

	osubbillingschedulesdk "github.com/oracle/oci-go-sdk/v65/osubbillingschedule"
	osubbillingschedulev1beta1 "github.com/oracle/oci-service-operator/api/osubbillingschedule/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// BillingScheduleServiceClient is the handwritten extension seam for BillingSchedule runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*BillingScheduleServiceManager).WithClient.
type BillingScheduleServiceClient interface {
	CreateOrUpdate(context.Context, *osubbillingschedulev1beta1.BillingSchedule, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *osubbillingschedulev1beta1.BillingSchedule) (bool, error)
}

type defaultBillingScheduleServiceClient struct {
	generatedruntime.ServiceClient[*osubbillingschedulev1beta1.BillingSchedule]
}

var _ BillingScheduleServiceClient = defaultBillingScheduleServiceClient{}

var newBillingScheduleServiceClient = func(manager *BillingScheduleServiceManager) BillingScheduleServiceClient {
	sdkClient, err := osubbillingschedulesdk.NewBillingScheduleClientWithConfigurationProvider(manager.Provider)
	hooks := newBillingScheduleRuntimeHooks(manager, sdkClient)
	config := buildBillingScheduleGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize BillingSchedule OCI client: %w", err)
	}
	delegate := defaultBillingScheduleServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*osubbillingschedulev1beta1.BillingSchedule](config),
	}
	return wrapBillingScheduleGeneratedClient(hooks, delegate)
}
