apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/genericartifactscontent.oracle.com_genericartifactcontentbypaths.yaml
- bases/genericartifactscontent.oracle.com_genericartifactcontents.yaml
