/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package workitem

import (
	"context"
	"fmt"

	jmsutilssdk "github.com/oracle/oci-go-sdk/v65/jmsutils"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// WorkItemServiceClient is the handwritten extension seam for WorkItem runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*WorkItemServiceManager).WithClient.
type WorkItemServiceClient interface {
	CreateOrUpdate(context.Context, *jmsutilsv1beta1.WorkItem, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *jmsutilsv1beta1.WorkItem) (bool, error)
}

type defaultWorkItemServiceClient struct {
	generatedruntime.ServiceClient[*jmsutilsv1beta1.WorkItem]
}

var _ WorkItemServiceClient = defaultWorkItemServiceClient{}

var newWorkItemServiceClient = func(manager *WorkItemServiceManager) WorkItemServiceClient {
	sdkClient, err := jmsutilssdk.NewJmsUtilsClientWithConfigurationProvider(manager.Provider)
	hooks := newWorkItemRuntimeHooks(manager, sdkClient)
	config := buildWorkItemGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize WorkItem OCI client: %w", err)
	}
	delegate := defaultWorkItemServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*jmsutilsv1beta1.WorkItem](config),
	}
	return wrapWorkItemGeneratedClient(hooks, delegate)
}
