/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package multicloudresource

import (
	"context"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type MulticloudResourceRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *multicloudv1beta1.MulticloudResource, string) (any, error)
	BuildUpdateBody func(context.Context, *multicloudv1beta1.MulticloudResource, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*multicloudv1beta1.MulticloudResource]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.MulticloudResource]
	StatusHooks         generatedruntime.StatusHooks[*multicloudv1beta1.MulticloudResource]
	ParityHooks         generatedruntime.ParityHooks[*multicloudv1beta1.MulticloudResource]
	Async               generatedruntime.AsyncHooks[*multicloudv1beta1.MulticloudResource]
	DeleteHooks         generatedruntime.DeleteHooks[*multicloudv1beta1.MulticloudResource]
	List                runtimeOperationHooks[multicloudsdk.ListMulticloudResourcesRequest, multicloudsdk.ListMulticloudResourcesResponse]
	WrapGeneratedClient []func(MulticloudResourceServiceClient) MulticloudResourceServiceClient
}

type MulticloudResourceRuntimeHooksMutator func(*MulticloudResourceServiceManager, *MulticloudResourceRuntimeHooks)

var multicloudresourceRuntimeHooksMutators []MulticloudResourceRuntimeHooksMutator

func registerMulticloudResourceRuntimeHooksMutator(mutator MulticloudResourceRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	multicloudresourceRuntimeHooksMutators = append(multicloudresourceRuntimeHooksMutators, mutator)
}
func newMulticloudResourceDefaultRuntimeHooks(sdkClient multicloudsdk.MulticloudResourcesClient) MulticloudResourceRuntimeHooks {
	return MulticloudResourceRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*multicloudv1beta1.MulticloudResource]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*multicloudv1beta1.MulticloudResource]{},
		StatusHooks:     generatedruntime.StatusHooks[*multicloudv1beta1.MulticloudResource]{},
		ParityHooks:     generatedruntime.ParityHooks[*multicloudv1beta1.MulticloudResource]{},
		Async:           generatedruntime.AsyncHooks[*multicloudv1beta1.MulticloudResource]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*multicloudv1beta1.MulticloudResource]{},
		List: runtimeOperationHooks[multicloudsdk.ListMulticloudResourcesRequest, multicloudsdk.ListMulticloudResourcesResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "SubscriptionServiceName", RequestName: "subscriptionServiceName", Contribution: "query", PreferResourceID: false}, {FieldName: "SubscriptionId", RequestName: "subscriptionId", Contribution: "query", PreferResourceID: false}, {FieldName: "ResourceAnchorId", RequestName: "resourceAnchorId", Contribution: "query", PreferResourceID: false}, {FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}, {FieldName: "ExternalLocation", RequestName: "externalLocation", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request multicloudsdk.ListMulticloudResourcesRequest) (multicloudsdk.ListMulticloudResourcesResponse, error) {
				return sdkClient.ListMulticloudResources(ctx, request)
			},
		},
		WrapGeneratedClient: []func(MulticloudResourceServiceClient) MulticloudResourceServiceClient{},
	}
}

func newMulticloudResourceRuntimeHooks(manager *MulticloudResourceServiceManager, sdkClient multicloudsdk.MulticloudResourcesClient) MulticloudResourceRuntimeHooks {
	hooks := newMulticloudResourceDefaultRuntimeHooks(sdkClient)
	for _, mutator := range multicloudresourceRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildMulticloudResourceGeneratedRuntimeConfig(
	manager *MulticloudResourceServiceManager,
	hooks MulticloudResourceRuntimeHooks,
) generatedruntime.Config[*multicloudv1beta1.MulticloudResource] {
	return generatedruntime.Config[*multicloudv1beta1.MulticloudResource]{
		Kind:            "MulticloudResource",
		SDKName:         "MulticloudResource",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &multicloudsdk.ListMulticloudResourcesRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*multicloudsdk.ListMulticloudResourcesRequest))
			},
		},
	}
}

func wrapMulticloudResourceGeneratedClient(
	hooks MulticloudResourceRuntimeHooks,
	delegate MulticloudResourceServiceClient,
) MulticloudResourceServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
