/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package multicloudresource

import (
	"context"
	"fmt"

	multicloudsdk "github.com/oracle/oci-go-sdk/v65/multicloud"
	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// MulticloudResourceServiceClient is the handwritten extension seam for MulticloudResource runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*MulticloudResourceServiceManager).WithClient.
type MulticloudResourceServiceClient interface {
	CreateOrUpdate(context.Context, *multicloudv1beta1.MulticloudResource, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *multicloudv1beta1.MulticloudResource) (bool, error)
}

type defaultMulticloudResourceServiceClient struct {
	generatedruntime.ServiceClient[*multicloudv1beta1.MulticloudResource]
}

var _ MulticloudResourceServiceClient = defaultMulticloudResourceServiceClient{}

var newMulticloudResourceServiceClient = func(manager *MulticloudResourceServiceManager) MulticloudResourceServiceClient {
	sdkClient, err := multicloudsdk.NewMulticloudResourcesClientWithConfigurationProvider(manager.Provider)
	hooks := newMulticloudResourceRuntimeHooks(manager, sdkClient)
	config := buildMulticloudResourceGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize MulticloudResource OCI client: %w", err)
	}
	delegate := defaultMulticloudResourceServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*multicloudv1beta1.MulticloudResource](config),
	}
	return wrapMulticloudResourceGeneratedClient(hooks, delegate)
}
