/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AnalyzeApplicationsConfigurationSpec defines the desired state of AnalyzeApplicationsConfiguration.
type AnalyzeApplicationsConfigurationSpec struct {
	// The Object Storage namespace used for analyzing applications.
	// +kubebuilder:validation:Optional
	NamespaceName string `json:"namespaceName,omitempty"`
	// The name of the bucket used for analyzing applications.
	// +kubebuilder:validation:Optional
	BucketName string `json:"bucketName,omitempty"`
}

// AnalyzeApplicationsConfigurationStatus defines the observed state of AnalyzeApplicationsConfiguration.
type AnalyzeApplicationsConfigurationStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The Object Storage namespace used for analyzing applications.
	NamespaceName string `json:"namespaceName,omitempty"`
	// The name of the bucket used for analyzing applications.
	BucketName string `json:"bucketName,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the AnalyzeApplicationsConfiguration",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the AnalyzeApplicationsConfiguration",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// AnalyzeApplicationsConfiguration is the Schema for the analyzeapplicationsconfigurations API.
type AnalyzeApplicationsConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AnalyzeApplicationsConfigurationSpec   `json:"spec,omitempty"`
	Status AnalyzeApplicationsConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// AnalyzeApplicationsConfigurationList contains a list of AnalyzeApplicationsConfiguration.
type AnalyzeApplicationsConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AnalyzeApplicationsConfiguration `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AnalyzeApplicationsConfiguration{}, &AnalyzeApplicationsConfigurationList{})
}
