/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// JavaMigrationAnalysisSpec defines the desired state of JavaMigrationAnalysis.
type JavaMigrationAnalysisSpec struct {
	// The OCID of the compartment where the Java Migration Analysis will be requested.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// Name of the analysis project.
	// +kubebuilder:validation:Required
	AnalysisProjectName string `json:"analysisProjectName"`
	// Object Storage paths to the input application files to analyze.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems=1
	InputApplicationsObjectStoragePaths []string `json:"inputApplicationsObjectStoragePaths"`
	// Target JDK version for this Java Migration Analysis.
	// +kubebuilder:validation:Required
	TargetJdkVersion string `json:"targetJdkVersion"`
}

// JavaMigrationAnalysisCreatedBy defines nested fields for JavaMigrationAnalysis.CreatedBy.
type JavaMigrationAnalysisCreatedBy struct {
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the principal.
	Id string `json:"id,omitempty"`
	// The name of the principal.
	DisplayName string `json:"displayName,omitempty"`
}

// JavaMigrationAnalysisStatus defines the observed state of JavaMigrationAnalysis.
type JavaMigrationAnalysisStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Java Migration Analysis.
	Id string `json:"id,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Work Request.
	WorkRequestId string `json:"workRequestId,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
	CompartmentId string `json:"compartmentId,omitempty"`
	// Name of the analysis project.
	AnalysisProjectName string `json:"analysisProjectName,omitempty"`
	// Object storage paths to the input files applications to be analysed.
	InputApplicationsObjectStoragePaths []string `json:"inputApplicationsObjectStoragePaths,omitempty"`
	// Jdk Version of the Java Migration Analysis target.
	TargetJdkVersion string `json:"targetJdkVersion,omitempty"`
	// Object storage namespace.
	NamespaceName string `json:"namespaceName,omitempty"`
	// Object storage bucket name.
	BucketName string `json:"bucketName,omitempty"`
	// Path to the Object Storage analysis application result.
	AnalysisResultObjectStoragePath string `json:"analysisResultObjectStoragePath,omitempty"`
	// The analysis application file names result in the Object Storage.
	AnalysisResultFiles []string `json:"analysisResultFiles,omitempty"`
	// The date and time the Java Migration Analysis was created, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeCreated string `json:"timeCreated,omitempty"`
	// The date and time the Java Migration Analysis was started, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeStarted string `json:"timeStarted,omitempty"`
	// The date and time the Java Migration Analysis was finished, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeFinished string                         `json:"timeFinished,omitempty"`
	CreatedBy    JavaMigrationAnalysisCreatedBy `json:"createdBy,omitempty"`
	// Additional info reserved for future use.
	Metadata string `json:"metadata,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the JavaMigrationAnalysis",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the JavaMigrationAnalysis",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// JavaMigrationAnalysis is the Schema for the javamigrationanalysis API.
type JavaMigrationAnalysis struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   JavaMigrationAnalysisSpec   `json:"spec,omitempty"`
	Status JavaMigrationAnalysisStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// JavaMigrationAnalysisList contains a list of JavaMigrationAnalysis.
type JavaMigrationAnalysisList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []JavaMigrationAnalysis `json:"items"`
}

func init() {
	SchemeBuilder.Register(&JavaMigrationAnalysis{}, &JavaMigrationAnalysisList{})
}
