/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PerformanceTuningAnalysisSpec defines the desired state of PerformanceTuningAnalysis.
type PerformanceTuningAnalysisSpec struct {
}

// PerformanceTuningAnalysisCreatedBy defines nested fields for PerformanceTuningAnalysis.CreatedBy.
type PerformanceTuningAnalysisCreatedBy struct {
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the principal.
	Id string `json:"id,omitempty"`
	// The name of the principal.
	DisplayName string `json:"displayName,omitempty"`
}

// PerformanceTuningAnalysisStatus defines the observed state of PerformanceTuningAnalysis.
type PerformanceTuningAnalysisStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Performance Tuning Analysis.
	Id string `json:"id,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Work Request.
	WorkRequestId string `json:"workRequestId,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
	CompartmentId string `json:"compartmentId,omitempty"`
	// Name of the analysis project.
	AnalysisProjectName string `json:"analysisProjectName,omitempty"`
	// Number of warnings in the Performance Tuning Analysis.
	WarningCount int `json:"warningCount,omitempty"`
	// Possible Performance Tuning Result statuses.
	Result string `json:"result,omitempty"`
	// Object storage path to the analysis.
	ResultObjectStoragePath string `json:"resultObjectStoragePath,omitempty"`
	// Object storage path to the artifact.
	ArtifactObjectStoragePath string `json:"artifactObjectStoragePath,omitempty"`
	// The date and time the Performance Tuning Analysis was created, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeCreated string `json:"timeCreated,omitempty"`
	// The date and time the Performance Tuning Analysis was started, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeStarted string `json:"timeStarted,omitempty"`
	// The date and time the Performance Tuning Analysis was finished, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeFinished string                             `json:"timeFinished,omitempty"`
	CreatedBy    PerformanceTuningAnalysisCreatedBy `json:"createdBy,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the PerformanceTuningAnalysis",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the PerformanceTuningAnalysis",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// PerformanceTuningAnalysis is the Schema for the performancetuninganalysis API.
type PerformanceTuningAnalysis struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PerformanceTuningAnalysisSpec   `json:"spec,omitempty"`
	Status PerformanceTuningAnalysisStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// PerformanceTuningAnalysisList contains a list of PerformanceTuningAnalysis.
type PerformanceTuningAnalysisList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PerformanceTuningAnalysis `json:"items"`
}

func init() {
	SchemeBuilder.Register(&PerformanceTuningAnalysis{}, &PerformanceTuningAnalysisList{})
}
