/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SubscriptionAcknowledgmentConfigurationSpec defines the desired state of SubscriptionAcknowledgmentConfiguration.
type SubscriptionAcknowledgmentConfigurationSpec struct {
	// Flag to determine whether the subscription was acknowledged or not.
	// +kubebuilder:validation:Optional
	IsAcknowledged bool `json:"isAcknowledged,omitempty"`
}

// SubscriptionAcknowledgmentConfigurationStatus defines the observed state of SubscriptionAcknowledgmentConfiguration.
type SubscriptionAcknowledgmentConfigurationStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// Flag to determine whether the subscription was acknowledged or not.
	IsAcknowledged bool `json:"isAcknowledged,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the principal that ackwnoledged the subscription.
	AcknowledgedBy string `json:"acknowledgedBy,omitempty"`
	// The date and time the subscription was acknowledged (formatted according to RFC3339 (https://datatracker.ietf.org/doc/html/rfc3339)).
	TimeAcknowledged string `json:"timeAcknowledged,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the SubscriptionAcknowledgmentConfiguration",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the SubscriptionAcknowledgmentConfiguration",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// SubscriptionAcknowledgmentConfiguration is the Schema for the subscriptionacknowledgmentconfigurations API.
type SubscriptionAcknowledgmentConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SubscriptionAcknowledgmentConfigurationSpec   `json:"spec,omitempty"`
	Status SubscriptionAcknowledgmentConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// SubscriptionAcknowledgmentConfigurationList contains a list of SubscriptionAcknowledgmentConfiguration.
type SubscriptionAcknowledgmentConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SubscriptionAcknowledgmentConfiguration `json:"items"`
}

func init() {
	SchemeBuilder.Register(&SubscriptionAcknowledgmentConfiguration{}, &SubscriptionAcknowledgmentConfigurationList{})
}
