/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WorkItemSpec defines the desired state of WorkItem.
type WorkItemSpec struct {
}

// WorkItemDetails defines nested fields for WorkItem.Details.
type WorkItemDetails struct {
	JsonData string `json:"jsonData,omitempty"`
	// The work item type.
	WorkItemType string `json:"workItemType,omitempty"`
	Kind         string `json:"kind,omitempty"`
	// Object storage path to the artifact.
	ArtifactObjectStoragePath string `json:"artifactObjectStoragePath,omitempty"`
	// Name of the analysis project.
	AnalysisProjectName string `json:"analysisProjectName,omitempty"`
	// The JDK version against which the migration analysis was performed to identify effort required to move from source JDK.
	TargetJdkVersion string `json:"targetJdkVersion,omitempty"`
	// Object storage path to the input artifact/s in the form of a serialized array.
	// Example: "[\"/JMS/Utils/myartifacts1.jar\",\"/JMS/Utils/myartifacts2.war\"]"
	InputApplicationsObjectStoragePaths string `json:"inputApplicationsObjectStoragePaths,omitempty"`
}

// WorkItemStatus defines the observed state of WorkItem.
type WorkItemStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The unique ID of ths work item.
	Id string `json:"id,omitempty"`
	// The OCID of the work request created this work item.
	WorkRequestId string `json:"workRequestId,omitempty"`
	// The status of the work item.
	// This uses a distinct JSON name so it can coexist with the OSOK status envelope.
	Status  string          `json:"sdkStatus,omitempty"`
	Details WorkItemDetails `json:"details,omitempty"`
	// Number of times this work item is retried.
	RetryCount int `json:"retryCount,omitempty"`
	// The date and time the work item was last updated. (formatted according to RFC3339 (https://datatracker.ietf.org/doc/html/rfc3339)).
	TimeLastUpdated string `json:"timeLastUpdated,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the WorkItem",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the WorkItem",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// WorkItem is the Schema for the workitems API.
type WorkItem struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   WorkItemSpec   `json:"spec,omitempty"`
	Status WorkItemStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// WorkItemList contains a list of WorkItem.
type WorkItemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkItem `json:"items"`
}

func init() {
	SchemeBuilder.Register(&WorkItem{}, &WorkItemList{})
}
