//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzeApplicationsConfiguration) DeepCopyInto(out *AnalyzeApplicationsConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzeApplicationsConfiguration.
func (in *AnalyzeApplicationsConfiguration) DeepCopy() *AnalyzeApplicationsConfiguration {
	if in == nil {
		return nil
	}
	out := new(AnalyzeApplicationsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyzeApplicationsConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzeApplicationsConfigurationList) DeepCopyInto(out *AnalyzeApplicationsConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnalyzeApplicationsConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzeApplicationsConfigurationList.
func (in *AnalyzeApplicationsConfigurationList) DeepCopy() *AnalyzeApplicationsConfigurationList {
	if in == nil {
		return nil
	}
	out := new(AnalyzeApplicationsConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyzeApplicationsConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzeApplicationsConfigurationSpec) DeepCopyInto(out *AnalyzeApplicationsConfigurationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzeApplicationsConfigurationSpec.
func (in *AnalyzeApplicationsConfigurationSpec) DeepCopy() *AnalyzeApplicationsConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(AnalyzeApplicationsConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzeApplicationsConfigurationStatus) DeepCopyInto(out *AnalyzeApplicationsConfigurationStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzeApplicationsConfigurationStatus.
func (in *AnalyzeApplicationsConfigurationStatus) DeepCopy() *AnalyzeApplicationsConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(AnalyzeApplicationsConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaMigrationAnalysis) DeepCopyInto(out *JavaMigrationAnalysis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaMigrationAnalysis.
func (in *JavaMigrationAnalysis) DeepCopy() *JavaMigrationAnalysis {
	if in == nil {
		return nil
	}
	out := new(JavaMigrationAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JavaMigrationAnalysis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaMigrationAnalysisCreatedBy) DeepCopyInto(out *JavaMigrationAnalysisCreatedBy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaMigrationAnalysisCreatedBy.
func (in *JavaMigrationAnalysisCreatedBy) DeepCopy() *JavaMigrationAnalysisCreatedBy {
	if in == nil {
		return nil
	}
	out := new(JavaMigrationAnalysisCreatedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaMigrationAnalysisList) DeepCopyInto(out *JavaMigrationAnalysisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JavaMigrationAnalysis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaMigrationAnalysisList.
func (in *JavaMigrationAnalysisList) DeepCopy() *JavaMigrationAnalysisList {
	if in == nil {
		return nil
	}
	out := new(JavaMigrationAnalysisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JavaMigrationAnalysisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaMigrationAnalysisSpec) DeepCopyInto(out *JavaMigrationAnalysisSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaMigrationAnalysisSpec.
func (in *JavaMigrationAnalysisSpec) DeepCopy() *JavaMigrationAnalysisSpec {
	if in == nil {
		return nil
	}
	out := new(JavaMigrationAnalysisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaMigrationAnalysisStatus) DeepCopyInto(out *JavaMigrationAnalysisStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.InputApplicationsObjectStoragePaths != nil {
		in, out := &in.InputApplicationsObjectStoragePaths, &out.InputApplicationsObjectStoragePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AnalysisResultFiles != nil {
		in, out := &in.AnalysisResultFiles, &out.AnalysisResultFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.CreatedBy = in.CreatedBy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaMigrationAnalysisStatus.
func (in *JavaMigrationAnalysisStatus) DeepCopy() *JavaMigrationAnalysisStatus {
	if in == nil {
		return nil
	}
	out := new(JavaMigrationAnalysisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTuningAnalysis) DeepCopyInto(out *PerformanceTuningAnalysis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTuningAnalysis.
func (in *PerformanceTuningAnalysis) DeepCopy() *PerformanceTuningAnalysis {
	if in == nil {
		return nil
	}
	out := new(PerformanceTuningAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerformanceTuningAnalysis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTuningAnalysisCreatedBy) DeepCopyInto(out *PerformanceTuningAnalysisCreatedBy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTuningAnalysisCreatedBy.
func (in *PerformanceTuningAnalysisCreatedBy) DeepCopy() *PerformanceTuningAnalysisCreatedBy {
	if in == nil {
		return nil
	}
	out := new(PerformanceTuningAnalysisCreatedBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTuningAnalysisList) DeepCopyInto(out *PerformanceTuningAnalysisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PerformanceTuningAnalysis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTuningAnalysisList.
func (in *PerformanceTuningAnalysisList) DeepCopy() *PerformanceTuningAnalysisList {
	if in == nil {
		return nil
	}
	out := new(PerformanceTuningAnalysisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerformanceTuningAnalysisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTuningAnalysisSpec) DeepCopyInto(out *PerformanceTuningAnalysisSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTuningAnalysisSpec.
func (in *PerformanceTuningAnalysisSpec) DeepCopy() *PerformanceTuningAnalysisSpec {
	if in == nil {
		return nil
	}
	out := new(PerformanceTuningAnalysisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTuningAnalysisStatus) DeepCopyInto(out *PerformanceTuningAnalysisStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	out.CreatedBy = in.CreatedBy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTuningAnalysisStatus.
func (in *PerformanceTuningAnalysisStatus) DeepCopy() *PerformanceTuningAnalysisStatus {
	if in == nil {
		return nil
	}
	out := new(PerformanceTuningAnalysisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionAcknowledgmentConfiguration) DeepCopyInto(out *SubscriptionAcknowledgmentConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionAcknowledgmentConfiguration.
func (in *SubscriptionAcknowledgmentConfiguration) DeepCopy() *SubscriptionAcknowledgmentConfiguration {
	if in == nil {
		return nil
	}
	out := new(SubscriptionAcknowledgmentConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubscriptionAcknowledgmentConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionAcknowledgmentConfigurationList) DeepCopyInto(out *SubscriptionAcknowledgmentConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubscriptionAcknowledgmentConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionAcknowledgmentConfigurationList.
func (in *SubscriptionAcknowledgmentConfigurationList) DeepCopy() *SubscriptionAcknowledgmentConfigurationList {
	if in == nil {
		return nil
	}
	out := new(SubscriptionAcknowledgmentConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubscriptionAcknowledgmentConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionAcknowledgmentConfigurationSpec) DeepCopyInto(out *SubscriptionAcknowledgmentConfigurationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionAcknowledgmentConfigurationSpec.
func (in *SubscriptionAcknowledgmentConfigurationSpec) DeepCopy() *SubscriptionAcknowledgmentConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(SubscriptionAcknowledgmentConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionAcknowledgmentConfigurationStatus) DeepCopyInto(out *SubscriptionAcknowledgmentConfigurationStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionAcknowledgmentConfigurationStatus.
func (in *SubscriptionAcknowledgmentConfigurationStatus) DeepCopy() *SubscriptionAcknowledgmentConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(SubscriptionAcknowledgmentConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkItem) DeepCopyInto(out *WorkItem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkItem.
func (in *WorkItem) DeepCopy() *WorkItem {
	if in == nil {
		return nil
	}
	out := new(WorkItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkItem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkItemDetails) DeepCopyInto(out *WorkItemDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkItemDetails.
func (in *WorkItemDetails) DeepCopy() *WorkItemDetails {
	if in == nil {
		return nil
	}
	out := new(WorkItemDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkItemList) DeepCopyInto(out *WorkItemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkItemList.
func (in *WorkItemList) DeepCopy() *WorkItemList {
	if in == nil {
		return nil
	}
	out := new(WorkItemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkItemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkItemSpec) DeepCopyInto(out *WorkItemSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkItemSpec.
func (in *WorkItemSpec) DeepCopy() *WorkItemSpec {
	if in == nil {
		return nil
	}
	out := new(WorkItemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkItemStatus) DeepCopyInto(out *WorkItemStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	out.Details = in.Details
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkItemStatus.
func (in *WorkItemStatus) DeepCopy() *WorkItemStatus {
	if in == nil {
		return nil
	}
	out := new(WorkItemStatus)
	in.DeepCopyInto(out)
	return out
}
