apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/jmsutils.oracle.com_analyzeapplicationsconfigurations.yaml
- bases/jmsutils.oracle.com_javamigrationanalyses.yaml
- bases/jmsutils.oracle.com_performancetuninganalyses.yaml
- bases/jmsutils.oracle.com_subscriptionacknowledgmentconfigurations.yaml
- bases/jmsutils.oracle.com_workitems.yaml
