/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package javamigrationanalysis

import (
	"context"
	"fmt"

	jmsutilssdk "github.com/oracle/oci-go-sdk/v65/jmsutils"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// JavaMigrationAnalysisServiceClient is the handwritten extension seam for JavaMigrationAnalysis runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*JavaMigrationAnalysisServiceManager).WithClient.
type JavaMigrationAnalysisServiceClient interface {
	CreateOrUpdate(context.Context, *jmsutilsv1beta1.JavaMigrationAnalysis, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *jmsutilsv1beta1.JavaMigrationAnalysis) (bool, error)
}

type defaultJavaMigrationAnalysisServiceClient struct {
	generatedruntime.ServiceClient[*jmsutilsv1beta1.JavaMigrationAnalysis]
}

var _ JavaMigrationAnalysisServiceClient = defaultJavaMigrationAnalysisServiceClient{}

var newJavaMigrationAnalysisServiceClient = func(manager *JavaMigrationAnalysisServiceManager) JavaMigrationAnalysisServiceClient {
	sdkClient, err := jmsutilssdk.NewJmsUtilsClientWithConfigurationProvider(manager.Provider)
	hooks := newJavaMigrationAnalysisRuntimeHooks(manager, sdkClient)
	config := buildJavaMigrationAnalysisGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize JavaMigrationAnalysis OCI client: %w", err)
	}
	delegate := defaultJavaMigrationAnalysisServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*jmsutilsv1beta1.JavaMigrationAnalysis](config),
	}
	return wrapJavaMigrationAnalysisGeneratedClient(hooks, delegate)
}
