/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package javamigrationanalysis

import (
	"context"

	jmsutilssdk "github.com/oracle/oci-go-sdk/v65/jmsutils"
	jmsutilsv1beta1 "github.com/oracle/oci-service-operator/api/jmsutils/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type JavaMigrationAnalysisRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *jmsutilsv1beta1.JavaMigrationAnalysis, string) (any, error)
	BuildUpdateBody func(context.Context, *jmsutilsv1beta1.JavaMigrationAnalysis, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]
	StatusHooks         generatedruntime.StatusHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]
	ParityHooks         generatedruntime.ParityHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]
	Async               generatedruntime.AsyncHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]
	DeleteHooks         generatedruntime.DeleteHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]
	Get                 runtimeOperationHooks[jmsutilssdk.GetJavaMigrationAnalysisRequest, jmsutilssdk.GetJavaMigrationAnalysisResponse]
	List                runtimeOperationHooks[jmsutilssdk.ListJavaMigrationAnalysisRequest, jmsutilssdk.ListJavaMigrationAnalysisResponse]
	Delete              runtimeOperationHooks[jmsutilssdk.DeleteJavaMigrationAnalysisRequest, jmsutilssdk.DeleteJavaMigrationAnalysisResponse]
	WrapGeneratedClient []func(JavaMigrationAnalysisServiceClient) JavaMigrationAnalysisServiceClient
}

type JavaMigrationAnalysisRuntimeHooksMutator func(*JavaMigrationAnalysisServiceManager, *JavaMigrationAnalysisRuntimeHooks)

var javamigrationanalysisRuntimeHooksMutators []JavaMigrationAnalysisRuntimeHooksMutator

func registerJavaMigrationAnalysisRuntimeHooksMutator(mutator JavaMigrationAnalysisRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	javamigrationanalysisRuntimeHooksMutators = append(javamigrationanalysisRuntimeHooksMutators, mutator)
}
func newJavaMigrationAnalysisDefaultRuntimeHooks(sdkClient jmsutilssdk.JmsUtilsClient) JavaMigrationAnalysisRuntimeHooks {
	return JavaMigrationAnalysisRuntimeHooks{
		Identity:        generatedruntime.IdentityHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]{},
		StatusHooks:     generatedruntime.StatusHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]{},
		ParityHooks:     generatedruntime.ParityHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]{},
		Async:           generatedruntime.AsyncHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*jmsutilsv1beta1.JavaMigrationAnalysis]{},
		Get: runtimeOperationHooks[jmsutilssdk.GetJavaMigrationAnalysisRequest, jmsutilssdk.GetJavaMigrationAnalysisResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "JavaMigrationAnalysisId", RequestName: "javaMigrationAnalysisId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request jmsutilssdk.GetJavaMigrationAnalysisRequest) (jmsutilssdk.GetJavaMigrationAnalysisResponse, error) {
				return sdkClient.GetJavaMigrationAnalysis(ctx, request)
			},
		},
		List: runtimeOperationHooks[jmsutilssdk.ListJavaMigrationAnalysisRequest, jmsutilssdk.ListJavaMigrationAnalysisResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "Id", RequestName: "id", Contribution: "query", PreferResourceID: false}, {FieldName: "AnalysisProjectName", RequestName: "analysisProjectName", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request jmsutilssdk.ListJavaMigrationAnalysisRequest) (jmsutilssdk.ListJavaMigrationAnalysisResponse, error) {
				return sdkClient.ListJavaMigrationAnalysis(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[jmsutilssdk.DeleteJavaMigrationAnalysisRequest, jmsutilssdk.DeleteJavaMigrationAnalysisResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "JavaMigrationAnalysisId", RequestName: "javaMigrationAnalysisId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request jmsutilssdk.DeleteJavaMigrationAnalysisRequest) (jmsutilssdk.DeleteJavaMigrationAnalysisResponse, error) {
				return sdkClient.DeleteJavaMigrationAnalysis(ctx, request)
			},
		},
		WrapGeneratedClient: []func(JavaMigrationAnalysisServiceClient) JavaMigrationAnalysisServiceClient{},
	}
}

func newJavaMigrationAnalysisRuntimeHooks(manager *JavaMigrationAnalysisServiceManager, sdkClient jmsutilssdk.JmsUtilsClient) JavaMigrationAnalysisRuntimeHooks {
	hooks := newJavaMigrationAnalysisDefaultRuntimeHooks(sdkClient)
	for _, mutator := range javamigrationanalysisRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildJavaMigrationAnalysisGeneratedRuntimeConfig(
	manager *JavaMigrationAnalysisServiceManager,
	hooks JavaMigrationAnalysisRuntimeHooks,
) generatedruntime.Config[*jmsutilsv1beta1.JavaMigrationAnalysis] {
	return generatedruntime.Config[*jmsutilsv1beta1.JavaMigrationAnalysis]{
		Kind:            "JavaMigrationAnalysis",
		SDKName:         "JavaMigrationAnalysis",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.GetJavaMigrationAnalysisRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*jmsutilssdk.GetJavaMigrationAnalysisRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.ListJavaMigrationAnalysisRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*jmsutilssdk.ListJavaMigrationAnalysisRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &jmsutilssdk.DeleteJavaMigrationAnalysisRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*jmsutilssdk.DeleteJavaMigrationAnalysisRequest))
			},
		},
	}
}

func wrapJavaMigrationAnalysisGeneratedClient(
	hooks JavaMigrationAnalysisRuntimeHooks,
	delegate JavaMigrationAnalysisServiceClient,
) JavaMigrationAnalysisServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
