/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package multicloud

import (
	"context"

	multicloudv1beta1 "github.com/oracle/oci-service-operator/api/multicloud/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ExternalLocationMappingMetadataReconciler reconciles a ExternalLocationMappingMetadata object.
type ExternalLocationMappingMetadataReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=multicloud.oracle.com,resources=externallocationmappingmetadata,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=multicloud.oracle.com,resources=externallocationmappingmetadata/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=multicloud.oracle.com,resources=externallocationmappingmetadata/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *ExternalLocationMappingMetadataReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	externalLocationMappingMetadata := &multicloudv1beta1.ExternalLocationMappingMetadata{}
	return r.Reconciler.Reconcile(ctx, req, externalLocationMappingMetadata)
}

// SetupWithManager sets up the controller with the Manager.
func (r *ExternalLocationMappingMetadataReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&multicloudv1beta1.ExternalLocationMappingMetadata{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
